# AUTO-GENERATED by scripts/ci/generate_mcp_policy.py — DO NOT EDIT BY HAND.
# বাংলা মন্তব্য: এই ফাইল config/mcp_policy_schema.json থেকে generated (#2429)।
# হাতে সম্পাদনা নিষিদ্ধ — schema বদলালে generator চালান।
# Canonical schema SHA-256 (prefix): 8f3502cc8489d55c

from __future__ import annotations

SCHEMA_VERSION = "1.0.0"
SCHEMA_HASH = "8f3502cc8489d55c"
READ_ONLY_PROVIDERS: tuple[str, ...] = ["system", "health"]
READ_ONLY_KEYWORDS: tuple[str, ...] = ["read", "list", "summary", "status", "search", "get", "query", "fetch", "open", "verify"]
DEFAULT_RISK = "R3"

# provider → (action → risk) টেবিল + optional per-provider default risk
PROVIDER_RULES: dict[str, dict[str, str]] = {
    "render": {
        "actions": {"restart": "R2", "deploy": "R2", "suspend": "R4", "delete": "R6"},
    },
    "supabase": {
        "actions": {"restart": "R3", "delete_table": "R6", "drop_db": "R6", "insert": "R2", "update": "R2"},
    },
    "redis": {
        "actions": {"flushall": "R5", "set": "R1", "del": "R2"},
    },
    "github": {
        "actions": {"commit": "R2", "push": "R2", "delete_repo": "R6"},
    },
    "agent_tools": {
        "actions": {"execute": "R5", "execute_code": "R5", "health": "R0", "search": "R0", "read": "R0", "status": "R0", "verify": "R0"},
        "default": "R3",
    },
    "memory": {
        "actions": {"delete": "R2", "clear": "R2", "drop": "R2", "create": "R1", "add": "R1", "store": "R1", "save": "R1", "record": "R1", "remember": "R1", "ingest": "R1"},
        "default": "R0",
    },
    "mcp_tools": {
        "actions": {"refresh": "R2", "live_query": "R2"},
        "default": "R0",
    },
    "mesh": {
        "actions": {"dispatch": "R1", "release": "R1", "renew": "R1", "send": "R1", "inbox": "R1", "ack": "R1", "subscribe": "R1"},
        "default": "R0",
    },
}

# tool → (provider, action) mapping
TOOL_PROVIDER_ACTION: dict[str, tuple[str, str]] = {
    "search_database": ("agent_tools", "search"),
    "check_system_health": ("agent_tools", "health"),
    "execute_python_code": ("agent_tools", "execute"),
    "cot_verify_math": ("agent_tools", "verify"),
    "create_entities": ("memory", "create"),
    "create_relations": ("memory", "create"),
    "add_observations": ("memory", "add"),
    "delete_entities": ("memory", "delete"),
    "delete_observations": ("memory", "delete"),
    "delete_relations": ("memory", "delete"),
    "read_graph": ("memory", "read"),
    "search_nodes": ("memory", "search"),
    "open_nodes": ("memory", "open"),
    "store_document": ("memory", "store"),
    "search_semantic": ("memory", "search"),
    "ingest_document_rag": ("memory", "ingest"),
    "record_task": ("memory", "record"),
    "get_similar_tasks": ("memory", "search"),
    "get_recent_episodes": ("memory", "read"),
    "build_context": ("memory", "read"),
    "get_session_stats": ("memory", "status"),
    "clear_session": ("memory", "clear"),
    "remember_fact": ("memory", "remember"),
    "recall_facts": ("memory", "search"),
    "save_learned_fact": ("memory", "save"),
    "search_learned_facts": ("memory", "search"),
    "get_skill_dependencies": ("mcp_tools", "read"),
    "find_optimal_learning_path": ("mcp_tools", "read"),
    "get_render_deploy_preflight": ("mcp_tools", "read"),
    "get_render_account_status": ("mcp_tools", "read"),
    "refresh_render_account_status": ("mcp_tools", "refresh"),
    "mesh_dispatch_task": ("mesh", "dispatch"),
    "mesh_task_status": ("mesh", "status"),
    "mesh_release_task": ("mesh", "release"),
    "agent_send": ("mesh", "send"),
    "agent_inbox": ("mesh", "inbox"),
    "agent_ack": ("mesh", "ack"),
    "topic_subscribe": ("mesh", "subscribe"),
}

UNKNOWN_TOOL_MAPPING: tuple[str, str] = ("unknown", "unknown")

# risk level → policy decision
DECISION_MATRIX: dict[str, str] = {"R0": "ALLOW", "R1": "ALLOW", "R2": "REQUIRE_APPROVAL", "R3": "REQUIRE_APPROVAL", "R4": "REQUIRE_APPROVAL", "R5": "REQUIRE_APPROVAL", "R6": "REQUIRE_APPROVAL"}
