import React, { useState } from 'react';
import { InteractiveChatTab } from '../../components/admin/InteractiveChatTab';
import { BrowserPreview } from '../../components/customer/BrowserPreview';
import { MobileSimulator } from '../../components/customer/MobileSimulator';
import type { ChatMessage } from '../../services/chatService';
import { Bot, Code, Smartphone } from 'lucide-react';

export const AIStudio: React.FC = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'preview' | 'mobile'>('chat');
  const [code, setCode] = useState('<!-- Code generated by SupremeAI will appear here -->');

  const handleSend = async () => {
    if (!input.trim()) return;
    const userMsg: ChatMessage = { role: 'user', content: input };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    try {
      // Stub implementation. Connect to real chatService here if needed.
      setTimeout(() => {
        setMessages(prev => [...prev, { role: 'ai', content: 'This is a response from SupremeAI.' }]);
        setLoading(false);
      }, 1000);
    } catch (e) {
      setLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full w-full bg-surface-0 overflow-hidden">
      {/* Top contextual header for AI Studio */}
      <div className="h-12 border-b border-border surface-1 flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-4 text-xs font-medium">
          <button 
            onClick={() => setActiveTab('chat')}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-md transition-colors ${activeTab === 'chat' ? 'surface-3 text-accent-primary' : 'text-secondary hover:text-text hover:surface-2'}`}
          >
            <Bot size={14} /> Conversation
          </button>
          <button 
            onClick={() => setActiveTab('preview')}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-md transition-colors ${activeTab === 'preview' ? 'surface-3 text-accent-primary' : 'text-secondary hover:text-text hover:surface-2'}`}
          >
            <Code size={14} /> Browser Preview
          </button>
          <button 
            onClick={() => setActiveTab('mobile')}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-md transition-colors ${activeTab === 'mobile' ? 'surface-3 text-accent-primary' : 'text-secondary hover:text-text hover:surface-2'}`}
          >
            <Smartphone size={14} /> Mobile Simulator
          </button>
        </div>
        
        <div className="flex items-center gap-3 text-[10px] uppercase tracking-widest text-muted">
          <span className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span> Agent: Alpha
          </span>
          <span className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-accent-primary"></span> Model: Supreme-Core
          </span>
        </div>
      </div>

      <div className="flex-1 min-h-0 relative">
        {activeTab === 'chat' && (
          <div className="absolute inset-0 p-4">
            <InteractiveChatTab
              messages={messages}
              input={input}
              onInputChange={setInput}
              onSend={handleSend}
              loading={loading}
              onSaveToProject={() => {}}
              onPreview={(html) => {
                setCode(html);
                setActiveTab('preview');
              }}
            />
          </div>
        )}

        {activeTab === 'preview' && (
          <div className="absolute inset-0 p-4">
            <BrowserPreview html={code} />
          </div>
        )}

        {activeTab === 'mobile' && (
          <div className="absolute inset-0 p-4">
            <MobileSimulator html={code} />
          </div>
        )}
      </div>
    </div>
  );
};
