import React, { useState } from 'react';
import { InteractiveChatTab } from '../../components/admin/InteractiveChatTab';
import { BrowserPreview } from '../../components/customer/BrowserPreview';
import { MobileSimulator } from '../../components/customer/MobileSimulator';
import { sendMessageStream, type ChatMessage } from '../../services/chatService';
import { Bot, Code, Smartphone } from 'lucide-react';

export const AIStudio: React.FC = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'preview' | 'mobile'>('chat');
  const [code, setCode] = useState('<!-- Code generated by SupremeAI will appear here -->');

  const handleSend = async () => {
    if (!input.trim()) return;
    const userMsg: ChatMessage = { role: 'user', content: input };
    const draftMessage: ChatMessage = { role: 'ai', content: '' };
    setMessages(prev => [...prev, userMsg, draftMessage]);
    setInput('');
    setLoading(true);

    let streamed = '';
    await sendMessageStream(
      userMsg.content,
      (token) => {
        streamed += token;
        setMessages(prev => {
          const withoutDraft = prev.filter((message) => message !== draftMessage);
          return [...withoutDraft, { role: 'ai', content: streamed }];
        });
      },
      () => setLoading(false),
      (error) => {
        setMessages(prev => [...prev, { role: 'ai', content: `Unable to reach SupremeAI: ${error}` }]);
        setLoading(false);
      },
    );
  };

  return (
    <div className="relative flex h-full w-full flex-col overflow-hidden bg-[var(--sa-canvas)] text-[var(--sa-ink)]">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-48 bg-[radial-gradient(circle_at_50%_0%,rgba(34,211,238,0.12),transparent_64%)]" aria-hidden="true" />
      {/* AI Studio contextual header */}
      <div className="relative flex min-h-16 shrink-0 items-center justify-between border-b border-[var(--sa-border)] bg-[var(--sa-surface)]/80 px-4 backdrop-blur sm:px-6">
        <div className="flex items-center gap-4 text-xs font-medium">
          <button 
            onClick={() => setActiveTab('chat')}
            className={`flex items-center gap-2 rounded-[var(--sa-radius-sm)] border px-3 py-2 text-xs transition-colors ${activeTab === 'chat' ? 'border-[var(--sa-primary)] bg-[var(--sa-primary-soft)] text-[var(--sa-primary)]' : 'border-transparent text-[var(--sa-ink-muted)] hover:border-[var(--sa-border)] hover:bg-[var(--sa-surface-raised)] hover:text-[var(--sa-ink)]'}`}
          >
            <Bot size={14} /> Conversation
          </button>
          <button 
            onClick={() => setActiveTab('preview')}
            className={`flex items-center gap-2 rounded-[var(--sa-radius-sm)] border px-3 py-2 text-xs transition-colors ${activeTab === 'preview' ? 'border-[var(--sa-primary)] bg-[var(--sa-primary-soft)] text-[var(--sa-primary)]' : 'border-transparent text-[var(--sa-ink-muted)] hover:border-[var(--sa-border)] hover:bg-[var(--sa-surface-raised)] hover:text-[var(--sa-ink)]'}`}
          >
            <Code size={14} /> Browser Preview
          </button>
          <button 
            onClick={() => setActiveTab('mobile')}
            className={`flex items-center gap-2 rounded-[var(--sa-radius-sm)] border px-3 py-2 text-xs transition-colors ${activeTab === 'mobile' ? 'border-[var(--sa-primary)] bg-[var(--sa-primary-soft)] text-[var(--sa-primary)]' : 'border-transparent text-[var(--sa-ink-muted)] hover:border-[var(--sa-border)] hover:bg-[var(--sa-surface-raised)] hover:text-[var(--sa-ink)]'}`}
          >
            <Smartphone size={14} /> Mobile Simulator
          </button>
        </div>
        
        <div className="hidden items-center gap-4 text-[10px] uppercase tracking-widest text-[var(--sa-ink-muted)] sm:flex">
          <span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-emerald-400" />Agent: Alpha</span>
          <span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-[var(--sa-primary)]" />Model: Supreme-Core</span>
          <span className="rounded-full border border-[var(--sa-border)] px-2 py-1 text-[var(--sa-ink-muted)]">Context ready</span>
        </div>
      </div>

      <div className="flex-1 min-h-0 relative">
        {activeTab === 'chat' && (
          <div className="absolute inset-0 p-4">
            <InteractiveChatTab
              messages={messages}
              input={input}
              onInputChange={setInput}
              onSend={handleSend}
              loading={loading}
              onSaveToProject={() => {}}
              onPreview={(html) => {
                setCode(html);
                setActiveTab('preview');
              }}
            />
          </div>
        )}

        {activeTab === 'preview' && (
          <div className="absolute inset-0 p-4">
            <BrowserPreview html={code} />
          </div>
        )}

        {activeTab === 'mobile' && (
          <div className="absolute inset-0 p-4">
            <MobileSimulator html={code} />
          </div>
        )}
      </div>
    </div>
  );
};
