import logging
import os
from core.cache.redis_manager import get_redis_client

logger = logging.getLogger(__name__)


class AutoPRPipeline:
    """
    অটোমেটেড গিটহাব পিআর পাইপলাইন।
    এআই জেনারেটেড কোড ফিক্সের জন্য রিমোট রিপোজিটরিতে অটোমেটেড ব্রাঞ্চ ও PR তৈরি করে।
    মাল্টি-ইনস্ট্যান্স ক্লাউড রানে একই এররের জন্য একাধিক PR তৈরি রোধে Redis Lock ব্যবহার করা হয়েছে।
    """

    def __init__(self, repo_name: str = "paykaribazaronline/supremeai"):
        self.repo_name = repo_name
        self.redis = get_redis_client()

    def acquire_pr_lock(self, error_fingerprint: str, lock_ttl_seconds: int = 3600) -> bool:
        """
        রেডিস ডিস্ট্রিবিউটেড লক অর্জন করা।
        """
        lock_key = f"pr_lock:{error_fingerprint}"
        if not self.redis:
            logger.warning("[AutoPRPipeline] Redis unavailable, bypassing lock.")
            return True

        try:
            # setnx to ensure atomicity
            is_locked = self.redis.set(lock_key, "locked", ex=lock_ttl_seconds, nx=True)
            return bool(is_locked)
        except Exception as e:
            logger.error(f"[AutoPRPipeline] Redis lock error: {e}")
            return True

    def create_remediation_pr(
        self, error_fingerprint: str, file_path: str, patch_code: str, issue_summary: str
    ) -> str | None:
        """
        গিটহাবে এআই-জেনারেটেড ফিক্সের জন্য নতুন ব্রাঞ্চ তৈরি করে পিআর ওপেন করা।
        """
        if not self.acquire_pr_lock(error_fingerprint):
            logger.info(f"[AutoPRPipeline] PR creation skipped for '{error_fingerprint}' - Lock already active.")
            return None

        github_token = os.getenv("GITHUB_TOKEN")
        if not github_token:
            logger.warning("[AutoPRPipeline] GITHUB_TOKEN not set. Simulating PR creation.")
            pr_url = f"https://github.com/{self.repo_name}/pull/mock-{error_fingerprint[:8]}"
            logger.info(f"[AutoPRPipeline] Simulated PR created: {pr_url}")
            return pr_url

        try:
            from github import Github

            g = Github(github_token)
            repo = g.get_repo(self.repo_name)

            branch_name = f"agent/fix-{error_fingerprint[:8]}"
            main_branch = repo.get_branch("main")

            # Create branch from main
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)

            # Commit changes
            contents = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                path=file_path,
                message=f"fix(auto-healer): {issue_summary}",
                content=patch_code,
                sha=contents.sha,
                branch=branch_name,
            )

            # Create Pull Request
            pr = repo.create_pull(
                title=f"🤖 [Auto-Remediation] Fix for {issue_summary}",
                body=f"This PR was automatically generated by SupremeAI Predictive Self-Healing Mesh.\n\n**Issue Summary:** {issue_summary}\n**Target File:** `{file_path}`",
                head=branch_name,
                base="main",
            )
            logger.info(f"[AutoPRPipeline] PR successfully opened: {pr.html_url}")
            return pr.html_url
        except Exception as e:
            logger.error(f"[AutoPRPipeline] Failed to create GitHub PR: {e}")
            return None
