/**
 * SupremeAI Auto-Generated Contracts
 * ==================================
 * DO NOT EDIT MANUALLY. Generated by `scripts/sync_contracts.py`.
 * Synced directly from FastAPI backend Pydantic models.
 */

// ==========================================
// 1. Self-Assembling Studio Contracts
// ==========================================
export interface SelfAssembleRequest {
  goal: string;
  max_iterations?: number;
  project_context?: Record<string, unknown>;
  auto_install_deps?: boolean;
}

export interface SelfAssembleStep {
  step_id: string;
  agent_role: string;
  action: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  duration_ms: number;
}

export interface SelfAssembleResponse {
  assembly_id: string;
  status: 'SUCCESS' | 'FAILED' | 'PARTIAL';
  files_created: string[];
  test_pass_rate: number;
  iterations: number;
  steps: SelfAssembleStep[];
  execution_summary: string;
}

// ==========================================
// 2. 3D Live Brain Visualizer Contracts
// ==========================================
export interface BrainPulseNode {
  id: string;
  label: string;
  group: 'CORE' | 'MEMORY' | 'AGENT' | 'TOOL';
  intensity: number;
  activity_count: number;
}

export interface BrainPulseLink {
  source: string;
  target: string;
  weight: number;
  protocol: 'REST' | 'WS' | 'PUB_SUB' | 'INTERNAL';
}

export interface BrainSnapshot {
  timestamp: string;
  total_memories: number;
  active_agents: number;
  system_load: number;
  nodes: BrainPulseNode[];
  links: BrainPulseLink[];
}

// ==========================================
// 3. AI Chat & Session DNA Contracts
// ==========================================
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: string;
  model?: string;
}

export interface SessionDNA {
  session_id: string;
  user_intent_summary: string;
  topics_discussed: string[];
  active_file_context?: string[];
  created_at: string;
  last_active_at: string;
}

// ==========================================
// 4. Micro-Runtime Sandbox Execution Contracts
// ==========================================
export interface SandboxExecutionRequest {
  code: string;
  timeout_ms?: number;
  allowed_imports?: string[];
  max_memory_mb?: number;
}

export interface SandboxExecutionResult {
  stdout: string;
  stderr: string;
  execution_time_ms: number;
  is_safe: boolean;
  exit_code: number;
  error?: string;
}
