#!/usr/bin/env python3
"""STATUS.md proof-stamper — CI-প্রমিত সত্য স্ট্যাম্প (docs/generated/STATUS_PROOF.md).

বাংলা মন্তব্য: STATUS.md-এ হাতে লেখা "100% passed" ধরনের দাবি সময়ের সাথে
মৃত/মিথ্যা হয়ে যায় (V5/V6 অডিটে প্রমাণিত)। এই স্ক্রিপ্ট বিপরীত দিক থেকে কাজ
করে: এখনই প্রকৃত mission suite চালিয়ে প্রকৃত সংখ্যা, প্রকৃত commit SHA ও
সময়স্তম্প দিয়ে একটি প্রমাণ-ফাইল জেনারেট করে — সম্পূর্ণ dynamic, কোনো
hardcoded দাবি নেই। STATUS.md-তে শুধু একটি লিংক থাকবে, দাবি নয়।
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path


def run_missions(backend_dir: Path) -> tuple[int | None, str]:
    """বাংলা: mission suite চালিয়ে (passed, summary-line) ফেরত দেয়।"""
    env = {**os.environ, "DATABASE_URL": "sqlite+aiosqlite:///./test.db"}
    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", "tests/missions/", "-q", "--no-cov"],
            cwd=backend_dir,
            env=env,
            capture_output=True,
            text=True,
            timeout=600,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return None, "TIMEOUT (600s)"
    tail = (result.stdout or "").strip().splitlines()
    summary = tail[-1] if tail else f"exit={result.returncode}"
    passed = None
    for line in reversed(tail):
        if " passed" in line or " failed" in line or " error" in line:
            # উদা: "============================= 57 passed in 21.07s ============================="
            for token in line.split():
                if token.isdigit():
                    passed = int(token)
                    break
            break
    if result.returncode != 0 and passed is None:
        return None, summary
    return passed, summary


def git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True
        ).stdout.strip()[:12]
    except subprocess.CalledProcessError:
        return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate CI-proof status stamp")
    parser.add_argument("--backend-dir", default="backend")
    parser.add_argument("--output-md", default="docs/generated/STATUS_PROOF.md")
    parser.add_argument("--output-json", default="ci-reports/status-proof.json")
    parser.add_argument(
        "--skip-tests", action="store_true", help="local dry-run: pytest বাদ"
    )
    parser.add_argument("--run-url", default="", help="CI run URL (workflow থেকে দেওয়া)")
    args = parser.parse_args()

    backend_dir = Path(args.backend_dir)
    if not args.skip_tests:
        if not backend_dir.is_dir():
            print(
                f"[status-proof] backend dir not found: {backend_dir}", file=sys.stderr
            )
            return 1
        passed, summary = run_missions(backend_dir)
    else:
        passed, summary = None, "skipped (local dry-run)"

    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    sha = git_sha()
    ok = passed is not None and passed > 0
    verdict = f"✅ {passed} passed" if ok else f"❌ {summary}"

    md = "\n".join(
        [
            "<!-- AUTO-GENERATED by scripts/ci/build_status_proof.py — হাতে এডিট করবেন না -->",
            "# লাইভ প্রমাণ (Status Proof)",
            "",
            f"- **Commit:** `{sha}`",
            f"- **সময়:** {now}",
            f"- **Mission suite:** {verdict}",
            *([f"- **CI Run:** {args.run_url}"] if args.run_url else []),
            "",
            "বাংলা: এই ফাইলটি প্রতিটি রানে প্রকৃত ফলাফল থেকে পুনরায় তৈরি হয় —",
            "এখানকার দাবি হাতে লেখা নয়, তাই মৃত/মিথ্যা হওয়ার সুযোগ নেই।",
            "",
        ]
    )
    json_payload = {
        "commit": sha,
        "generated_at": now,
        "missions_passed": passed,
        "missions_summary": summary,
        "run_url": args.run_url,
        "ok": ok,
    }

    for target, content in (
        (args.output_md, md),
        (args.output_json, json.dumps(json_payload, indent=2) + "\n"),
    ):
        out = Path(target)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
        print(f"[status-proof] wrote {out}")

    # বাংলা: mission suite ব্যর্থ হলে গেটও ব্যর্থ হবে — নীরব সবুজ নয়
    # (dry-run/skip মোডে বিচার নেই — exit 0, কারণ এটা প্রমাণ নয়, শুধু ফাইল-প্রিভিউ)
    if args.skip_tests:
        return 0
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
