#!/usr/bin/env python3
"""
check_hardcoded_deployment_config.py
Scans the codebase for hardcoded production hostnames (e.g. .onrender.com).
Enforces zero-hardcode configuration policy.

SCRIPT-INTELLIGENCE v9: auto-discovers targets via scripts/lib/auto_discovery.py — no hardcoded file inventories.
Scan root, the frontend tree and exception anchors are resolved from the live
filesystem; a stale anchor (like the old "frontend/src/api.ts" example, which no
longer exists) is skipped with a clear "[discovery] ... skipping" warning instead
of silently disabling its exception.

Environment overrides:
  SCAN_ROOT            scan root pin (default: auto-discovered repo root)
  SUPREMEAI_REPO_ROOT  repo root pin (scripts/lib/auto_discovery.py)

Exit codes: 0 = pass, 1 = violations found, 2 = discovery/error (fail-loud)
"""

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # scripts/
from lib.auto_discovery import (  # noqa: E402
    DiscoveryError,
    discover_files,
    get_layout,
    require,
)

# Directories/files to skip
IGNORE_PATHS = {
    "node_modules",
    "dist",
    "dist-admin",
    "dist-user",
    ".playwright-mcp",
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".venv",
    "venv",
    "tests",
    "docs",
    "scripts/ci",
    "scripts/docs",
    "scripts/patches",
    "scripts/advanced_analysis",
    ".env.example",
    ".env",
    ".kilo",
    "secrets_registry.yaml",
    "README.md",
    "AGENTS.md",
    "STATUS.md",
    "CHECKPOINT.md",
    "REAL_TESTING_LOG.md",
    "ERROR_AUDIT.md",
    "reports",
    "specs",
    "audit_reports",
    ".agents",
    "_archive",
    ".github/workflows",
    "firebase.json",
    "htmlcov",
    "scripts/archive",
    "scripts/pre_merge_guard.py",
    # SCRIPT-INTELLIGENCE v9: the auto-discovery lib *derives* conventional
    # URLs from render.yaml service names (it holds no deployment pins of
    # its own) and _INDEX.md is auto-generated by
    # scripts/generate_script_index.py (regenerate it, never hand-edit).
    "scripts/lib/auto_discovery.py",
    "scripts/_INDEX.md",
    "out"
}

# File suffixes that are test fixtures — these intentionally reference
# deployment hostnames to simulate different environments and are not
# themselves hardcoded production configuration.
IGNORE_SUFFIXES = (
    ".test.ts",
    ".test.tsx",
    ".spec.ts",
    ".spec.tsx",
)

# The patterns we want to catch
BANNED_PATTERNS = [
    r"\.onrender\.com",
    r"\.web\.app",
    r"\.firebaseapp\.com",
    r"\.vercel\.app",
    r"supreme-admin-\d+-prod" # hardcoded passwords
]

BANNED_REGEX = re.compile("|".join(BANNED_PATTERNS), re.IGNORECASE)

# Allowed exceptions — SCRIPT-INTELLIGENCE v9: each anchor is resolved against
# the live filesystem at runtime.  Tuple shape:
#   (repo-relative anchor, line-regex, discovery-glob | None)
# A discovery-glob makes the anchor dynamic (frontend entry files are found
# wherever they live, e.g. "index.html" at the frontend root).  Anchors whose
# file genuinely does not exist anywhere are skipped with a "[discovery]"
# warning — never silently kept, never silently scanned-without-exception.
# (Illustrative-only example, kept for format documentation: the historical
#  ("frontend/src/api.ts", r"// Legacy endpoint: .*\.onrender\.com") entry —
#  that file no longer exists, so today it would warn-and-skip.)
EXCEPTION_SPECS: list[tuple[str, str, tuple[str, ...] | None]] = [
    (".github/scripts/ci_summary_v2.py", r"\.onrender\.com", None),
    # Pydantic Field() docstring examples — illustrative only, not a runtime default.
    ("backend/core/config_validator.py", r"examples=", None),
    # CSP allow-list uses wildcard host patterns (e.g. https://*.web.app), not a
    # specific deployment hostname, and must stay inline in the HTML head.
    # Frontend entry is DISCOVERED (glob), not hardcoded.
    ("frontend/index.html", r"Content-Security-Policy", ("index.html",)),
]


def resolve_exceptions(root: Path) -> tuple[list[tuple[str, str]], list[str]]:
    """Resolve EXCEPTION_SPECS against the live filesystem.

    Returns (resolved[(rel_path, line_regex)], warnings).  A stale anchor is
    dropped with a warning instead of silently never matching.
    """
    resolved: list[tuple[str, str]] = []
    warnings: list[str] = []
    layout = get_layout()

    for anchor, pattern, glob_pat in EXCEPTION_SPECS:
        if glob_pat is not None:
            # dynamic anchor: discover the file wherever it currently lives
            base = root
            if anchor.startswith("frontend") and layout.frontend and layout.frontend.is_dir():
                base = layout.frontend
            hits = discover_files(base, glob_pat)
            if not hits:
                warnings.append(
                    f"[discovery] exception anchor '{anchor}' (glob {glob_pat}) not found — skipping exception"
                )
                continue
            try:
                rel = hits[0].resolve().relative_to(root).as_posix()
            except ValueError:
                warnings.append(
                    f"[discovery] exception anchor {hits[0]} outside scan root — skipping exception"
                )
                continue
            resolved.append((rel, pattern))
            continue

        if (root / anchor).exists():
            resolved.append((anchor, pattern))
        else:
            warnings.append(
                f"[discovery] exception target '{anchor}' not found — skipping exception"
            )
    return resolved, warnings


def should_ignore(path: Path, root: Path) -> bool:
    try:
        rel_path = path.relative_to(root).as_posix()
    except ValueError:
        return True
    
    # We also ignore artifacts/logs
    if ".system_generated" in rel_path or ".gemini" in rel_path:
        return True

    if rel_path.endswith(IGNORE_SUFFIXES):
        return True

    path_parts = Path(rel_path).parts
    for ignore in IGNORE_PATHS:
        if rel_path.startswith(ignore) or rel_path == ignore:
            return True
        # Match a whole path segment — e.g. ignoring "tests" skips any
        # .../tests/... directory (illustrative filename: "backend/tests/x.py",
        # which does not exist in this repo; it only demonstrates the rule).
        if ignore in path_parts:
            return True
        # Match by filename anywhere in the tree (e.g. "REAL_TESTING_LOG.md")
        if path.name == ignore:
            return True
    return False

def scan_file(filepath: Path, root: Path, exceptions: list[tuple[str, str]]) -> list[str]:
    violations = []
    try:
        rel_path = filepath.relative_to(root).as_posix()
        content = filepath.read_text(encoding="utf-8")
        
        for line_num, line in enumerate(content.splitlines(), 1):
            if BANNED_REGEX.search(line):
                # Check exceptions
                is_exception = False
                for ex_file, ex_pattern in exceptions:
                    if ex_file == rel_path and re.search(ex_pattern, line):
                        is_exception = True
                        break
                
                if not is_exception:
                    violations.append(f"  ❌ Line {line_num}: {line.strip()}")
                    
    except Exception as e:
        # Ignore binary files or unreadable files
        _ = e
    return violations


def _print_usage() -> None:
    print(
        """ব্যবহার: check_hardcoded_deployment_config.py [অপশন]

অপশন:
  --help, -h    এই সাহায্য বার্তা

Environment:
  SCAN_ROOT            স্ক্যান রুট ওভাররাইড (ডিফল্ট: auto-discovered repo root)
  SUPREMEAI_REPO_ROOT  রিপো রুট ওভাররাইড (scripts/lib/auto_discovery.py)

Exit codes: 0 = pass | 1 = violations found | 2 = discovery/error (fail-loud)"""
    )


def main() -> int:
    if len(sys.argv) > 1:
        if any(a in ("--help", "-h") for a in sys.argv[1:]):
            _print_usage()
            return 0
        print(f"❌ অজানা অপশন: {' '.join(sys.argv[1:])}", file=sys.stderr)
        _print_usage()
        return 2

    if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
        sys.stdout.reconfigure(encoding='utf-8')

    try:
        env_root = os.getenv("SCAN_ROOT")
        if env_root:
            root = Path(env_root).resolve()
            if not root.is_dir():
                raise DiscoveryError(f"SCAN_ROOT={env_root!r} is not a directory")
        else:
            root = get_layout().root
        layout = get_layout()
    except DiscoveryError as exc:
        print(f"[discovery] {exc}", file=sys.stderr)
        return 2

    exceptions, exception_warnings = resolve_exceptions(root)

    # Frontend entry discovery — dynamic: scan whatever actually exists.
    frontend_note = str(layout.frontend) if layout.frontend else "(no frontend dir — skipping)"
    fe_entries: list[Path] = []
    if layout.frontend and layout.frontend.is_dir():
        fe_entries = discover_files(layout.frontend, ("src/**/*.ts", "src/**/*.tsx"))

    print("🔍 Scanning codebase for hardcoded deployment configuration...")
    print(
        f"[discovery] SCRIPT-INTELLIGENCE v9 | scan root: {root} | frontend: {frontend_note} | "
        f"frontend src entries: {len(fe_entries)} ts/tsx | "
        f"exceptions resolved: {len(exceptions)}/{len(EXCEPTION_SPECS)}"
    )
    for w in exception_warnings:
        print(w)
    if layout.frontend and layout.frontend.is_dir() and not fe_entries:
        print("[discovery] WARNING: frontend present but 0 src/**/*.ts(x) entries found — frontend layout changed?")

    has_errors = False
    scanned: list[Path] = []

    for root_dir, dirs, files in os.walk(root):
        # Filter directories in-place to avoid traversing ignored paths
        dirs[:] = [d for d in dirs if not should_ignore(Path(root_dir) / d, root)]
        
        for file in files:
            filepath = Path(root_dir) / file
            if should_ignore(filepath, root):
                continue
                
            # Only check likely source files
            if filepath.suffix not in {'.py', '.ts', '.tsx', '.js', '.jsx', '.json', '.yml', '.yaml', '.html', '.sh', '.md', ''}:
                continue

            scanned.append(filepath)
            violations = scan_file(filepath, root, exceptions)
            if violations:
                has_errors = True
                print(f"\n📄 {filepath.relative_to(root)}:")
                for v in violations:
                    print(v)

    # বাংলা: fail-loud — একটাও ফাইল স্ক্যান না হলে 'PASS' বলা যাবে না
    try:
        require(scanned, f"files to scan under {root}")
    except DiscoveryError as exc:
        print(f"[discovery] {exc}", file=sys.stderr)
        return 2

    print(f"[discovery] scanned {len(scanned)} files")

    if has_errors:
        print("\n🚨 Hardcoded deployment configuration detected! CI failed.")
        print("Please move these values to environment variables/Settings.")
        sys.exit(1)
    else:
        print("\n✅ PASS: No hardcoded deployment configuration found.")
        sys.exit(0)


if __name__ == "__main__":
    sys.exit(main())
