#!/usr/bin/env python3
"""Generate ``.env.example`` from the canonical CONFIG_SPECS registry (issue #1260).

Single source of truth: ``backend/core/config_classification.py::CONFIG_SPECS``.

Wave 3.4 (ENV registry 3→1): the env template used to be hand-maintained and
drifted away from the canonical registry (66 template keys unclassified,
13 canonical keys missing from the template). This script renders the template
from CONFIG_SPECS so the two can no longer drift silently:

* **Canonical section** — every CONFIG_SPECS name, grouped by category
  (the spec's primary scope: backend, frontend, ci, deploy, security,
  user-local), in registry declaration order. Each entry carries a comment
  and an example value:
    - comment: the previous template's curated comment block for that key if
      it had one, else the spec description (skipped when it is still an
      auto-classification placeholder or empty);
    - value: the previous template's example value if it had one, else empty.
* **Legacy / extra section** — template keys that are not canonical
  CONFIG_SPECS names (documented aliases and unclassified keys), preserved
  verbatim in their original order with their original comments, so no
  information is lost. Classifying a key in CONFIG_SPECS promotes it into the
  canonical section on the next regeneration.

Usage:
    python3 scripts/ci/generate_env_example.py            # regenerate in place
    python3 scripts/ci/generate_env_example.py --check    # CI: exit 1 if the
                                                          # committed file is
                                                          # not up to date

The script never prints or writes secret values — the template only ever
contains placeholders.
"""

from __future__ import annotations

import argparse
import difflib
import importlib.util
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLASSIFICATION = ROOT / "backend" / "core" / "config_classification.py"
ENV_EXAMPLE = ROOT / ".env.example"

# Primary-scope category order for the canonical sections.
CATEGORY_ORDER = ("backend", "frontend", "ci", "deploy", "security", "user-local")

KEY_LINE = re.compile(r"^(?P<key>[A-Za-z_][A-Za-z0-9_]*)=(?P<value>.*)$")
INLINE_COMMENT = re.compile(
    r"\s+#(?!\s*$)"
)  # whitespace + '#' starts an inline comment
BANNER = re.compile(
    r"^#\s*[─═=-]{2,}"
)  # structural section banners ("# ── X ──", "# ===")
PLACEHOLDER_DESC = re.compile(r"^Auto-classified by CI drift remediation")

CANONICAL_BANNER = """\
# =============================================================================
# CANONICAL SECTION — generated from backend/core/config_classification.py::CONFIG_SPECS
# (issue #1260, Wave 3.4: ENV registry 3→1). Do not hand-edit key order here.
# Regenerate with: python3 scripts/ci/generate_env_example.py
# Verify with:     python3 scripts/ci/generate_env_example.py --check
# Values are example placeholders inherited from the previous template — never
# commit real secret values.
# ============================================================================="""

LEGACY_BANNER = """\
# =============================================================================
# LEGACY / EXTRA KEYS — not in CONFIG_SPECS
# These template keys are documented aliases or are not yet classified in the
# canonical registry; comments below are preserved verbatim. Classify a key in
# CONFIG_SPECS to promote it into the canonical sections above, or delete it
# here if it is obsolete.
# ============================================================================="""

# Marks where the preserved human preamble ends and the generated body starts.
# Everything after this marker is regenerated on every run (idempotency).
GENERATED_MARKER = "# >>> body below is REGENERATED by scripts/ci/generate_env_example.py — edit CONFIG_SPECS, not this body <<<"
ALIAS_NOTE = "# documented alias of"


def load_registry():
    """Load the metadata-only registry as a real Python module (see
    scripts/ci/validate_config_registry.py for the sys.modules rationale)."""
    module_name = "supremeai_config_classification"
    spec = importlib.util.spec_from_file_location(module_name, CLASSIFICATION)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {CLASSIFICATION}")
    module = importlib.util.module_from_spec(spec)
    previous = sys.modules.get(module_name)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        if previous is None:
            sys.modules.pop(module_name, None)
        else:
            sys.modules[module_name] = previous
        raise
    return module.BY_NAME, module.ALIAS_TO_CANONICAL


class Entry:
    """One KEY=... line plus the comment block attached to it."""

    __slots__ = ("key", "value", "inline", "comments", "order")

    def __init__(
        self, key: str, value: str, inline: str, comments: list[str], order: int
    ):
        self.key = key
        self.value = value
        self.inline = inline
        self.comments = comments
        self.order = order

    def render(self) -> list[str]:
        lines = list(self.comments)
        line = f"{self.key}={self.value}"
        if self.inline:
            line = f"{line}  {self.inline}"
        lines.append(line)
        return lines


def split_inline(value: str) -> tuple[str, str]:
    """Split 'value  # comment' into (value, '# comment'); '' when absent."""
    m = INLINE_COMMENT.search(value)
    if not m:
        return value.rstrip(), ""
    head, tail = value[: m.start()].rstrip(), value[m.start() :].strip()
    return head, tail


def parse_template(text: str) -> tuple[list[str], dict[str, Entry], list[str]]:
    """Parse the current template into (preamble, entries by key, orphan notes).

    Duplicate keys are consolidated: the first occurrence supplies the example
    value, and the first non-empty comment block supplies the comments (both
    later occurrences are dropped — the pre-generation template had 19
    duplicate key lines).

    When the GENERATED_MARKER is present (already-generated file), the
    preamble stops at the marker so the generated body is never re-absorbed.
    """
    lines = text.splitlines()
    marker_idx = next(
        (i for i, l in enumerate(lines) if l.strip() == GENERATED_MARKER), None
    )
    body_start = (marker_idx + 1) if marker_idx is not None else None
    preamble: list[str] = []
    entries: dict[str, Entry] = {}
    order = 0
    i = 0
    # Preamble: everything before the first KEY=... line (or up to the marker).
    while i < len(lines):
        if body_start is not None and i == body_start:
            break
        if body_start is None and KEY_LINE.match(lines[i].strip()):
            break
        preamble.append(lines[i])
        i += 1
    if body_start is not None:
        preamble = lines[:body_start]
        i = body_start
    comments: list[str] = []
    while i < len(lines):
        stripped = lines[i].strip()
        m = KEY_LINE.match(stripped)
        if m:
            key = m.group("key")
            value, inline = split_inline(m.group("value"))
            if key in entries:
                prev = entries[key]
                if not prev.comments and comments:
                    prev.comments = comments
            else:
                entries[key] = Entry(key, value, inline, comments, order)
                order += 1
            comments = []
        elif stripped == "":
            comments = []
        elif stripped.startswith("#"):
            comments.append(lines[i].rstrip())
        else:
            # Malformed line — preserve it as an orphan note rather than crash.
            comments.append(lines[i].rstrip())
        i += 1
    return preamble, entries, comments


def category_for(scopes: frozenset[str]) -> str:
    for cat in CATEGORY_ORDER:
        if cat in scopes:
            return cat
    return sorted(scopes)[0] if scopes else "backend"


def non_placeholder_desc(desc: str) -> str:
    desc = desc.strip()
    if not desc or PLACEHOLDER_DESC.match(desc):
        return ""
    return desc


def build_comment_block(prev: Entry | None, spec_desc: str) -> list[str]:
    """Canonical-entry comment: previous curated block wins, else spec desc."""
    if prev is not None:
        kept = [c for c in prev.comments if not BANNER.match(c.strip())]
        if kept:
            return kept
    desc = non_placeholder_desc(spec_desc)
    return [f"# {desc}"] if desc else []


def generate(by_name: dict, aliases: dict, current: str) -> str:
    preamble, prev_entries, orphan_notes = parse_template(current)

    # --- canonical section, grouped by primary scope -------------------------
    groups: dict[str, list] = {}
    for spec in by_name.values():
        groups.setdefault(category_for(spec.scopes), []).append(spec)

    out: list[str] = list(preamble)
    if not (out and out[-1].strip() == GENERATED_MARKER):
        # First run over a hand-written template: drop trailing structural
        # banners/blank lines (regenerated below), then place the marker.
        while out and (out[-1].strip() == "" or BANNER.match(out[-1].strip())):
            out.pop()
        if out:
            out.append("")
        out.append(GENERATED_MARKER)
    out.append("")
    out.append(CANONICAL_BANNER)
    for cat in [c for c in CATEGORY_ORDER if c in groups] + sorted(
        set(groups) - set(CATEGORY_ORDER)
    ):
        specs = groups[cat]
        out.append("")
        keys_word = "keys" if len(specs) != 1 else "key"
        out.append(f"# ── Canonical keys — scope: {cat} ({len(specs)} {keys_word}) ──")
        out.append("")
        for spec in specs:
            block = build_comment_block(prev_entries.get(spec.name), spec.description)
            if block and out[-1] != "":
                out.append("")
            out.extend(block)
            prev = prev_entries.get(spec.name)
            value = prev.value if prev is not None else ""
            inline = prev.inline if prev is not None else ""
            line = f"{spec.name}={value}"
            if inline:
                line = f"{line}  {inline}"
            out.append(line)

    # --- legacy / extra section ----------------------------------------------
    legacy_keys = [k for k in prev_entries if k not in by_name]
    out.append("")
    out.append(LEGACY_BANNER)
    out.append(
        f"# ({len(legacy_keys)} keys — preserved verbatim from the previous template)"
    )
    out.append("")
    for key in legacy_keys:
        entry = prev_entries[key]
        comments = [c for c in entry.comments if not c.strip().startswith(ALIAS_NOTE)]
        canonical_of = aliases.get(key)
        if canonical_of is not None:
            comments.append(f"{ALIAS_NOTE} {canonical_of}")
        entry.comments = comments
        out.extend(entry.render())
    if orphan_notes:
        out.append("")
        out.append(
            "# ── Preserved notes (comment blocks from the previous template) ──"
        )
        out.extend(orphan_notes)
    out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate to a temp file and diff against the committed .env.example",
    )
    args = parser.parse_args()

    by_name, aliases = load_registry()
    current = ENV_EXAMPLE.read_text(encoding="utf-8") if ENV_EXAMPLE.exists() else ""
    rendered = generate(by_name, aliases, current)

    if args.check:
        if current == rendered:
            print(
                f"[PASS] {ENV_EXAMPLE.name} is up to date with CONFIG_SPECS "
                f"({len(by_name)} canonical keys)"
            )
            return 0
        with tempfile.NamedTemporaryFile(
            "w", suffix=".env.example", delete=False
        ) as fh:
            fh.write(rendered)
            tmp = fh.name
        diff = difflib.unified_diff(
            current.splitlines(),
            rendered.splitlines(),
            fromfile=".env.example (committed)",
            tofile=".env.example (generated)",
            lineterm="",
        )
        preview = list(diff)[:60]
        print(f"[FAIL] {ENV_EXAMPLE.name} is out of date with CONFIG_SPECS.", end="")
        if preview:
            print(" Diff preview (first 60 lines):")
            print("\n".join(preview))
        print(
            f"Full generated file written to {tmp} — "
            f"run `python3 scripts/ci/generate_env_example.py` to regenerate in place."
        )
        return 1

    ENV_EXAMPLE.write_text(rendered, encoding="utf-8")
    before = parse_template(current)[1]
    legacy = sum(1 for k in before if k not in by_name)
    print(
        f"[OK] regenerated {ENV_EXAMPLE} — {len(by_name)} canonical keys "
        f"({len(before)} unique keys before, {legacy} legacy keys preserved)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
