#!/usr/bin/env python3
"""Weekly changelog auto-generator (conventional commits → CHANGELOG.auto.md).

বাংলা মন্তব্য: গত N দিনের git log থেকে conventional-commit prefix অনুযায়ী
গ্রুপ করে CHANGELOG.auto.md তৈরি করে — সম্পূর্ণ dynamic (কোনো হার্ডকোডেড
এন্ট্রি নেই), deterministic (একই history = একই আউটপুট), bounded (প্রতি গ্রুপে
সর্বোচ্চ ৪০টি এন্ট্রি)। হাতে লেখা চেঞ্জলগের পিছিয়ে-থাকা সমস্যার শূন্য-খরচ সমাধান।
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from collections import defaultdict
from datetime import UTC, datetime, timedelta

# বাংলা: conventional-commit prefix → বাংলা সেকশন হেডার
GROUPS: list[tuple[str, str]] = [
    ("feat", "✨ নতুন ফিচার (feat)"),
    ("fix", "🐛 ফিক্স (fix)"),
    ("security", "🔐 সিকিউরিটি (security)"),
    ("perf", "⚡ পারফরম্যান্স (perf)"),
    ("refactor", "♻️ রিফ্যাক্টর (refactor)"),
    ("docs", "📚 ডকুমেন্টেশন (docs)"),
    ("test", "🧪 টেস্ট (test)"),
    ("chore", "🔧 কোরিয়া (chore)"),
]
MAX_PER_GROUP = 40
HEADER_MARK = (
    "<!-- AUTO-GENERATED by scripts/ci/generate_changelog.py — হাতে এডিট করবেন না -->"
)


def collect_subjects(days: int) -> list[str]:
    since = (datetime.now(UTC) - timedelta(days=days)).strftime("%Y-%m-%d")
    result = subprocess.run(
        ["git", "log", f"--since={since}", "--pretty=%s"],
        capture_output=True,
        text=True,
        check=True,
    )
    return [s.strip() for s in result.stdout.splitlines() if s.strip()]


def group_subjects(subjects: list[str]) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for subject in subjects:
        lower = subject.lower()
        for prefix, header in GROUPS:
            if lower.startswith((prefix + ":", prefix + "(")):
                grouped[header].append(subject)
                break
        else:
            grouped["📦 অন্যান্য (uncategorized)"].append(subject)
    return grouped


def render(grouped: dict[str, list[str]], days: int) -> str:
    today = datetime.now(UTC).strftime("%Y-%m-%d")
    since = (datetime.now(UTC) - timedelta(days=days)).strftime("%Y-%m-%d")
    lines = [HEADER_MARK, f"# Auto Changelog ({since} → {today})", ""]
    for _, header in GROUPS + [("📦 অন্যান্য (uncategorized)", "")]:
        items = grouped.get(header, [])
        if not items:
            continue
        lines.append(f"## {header} ({len(items)})")
        lines.append("")
        for subject in items[:MAX_PER_GROUP]:
            lines.append(f"- {subject}")
        if len(items) > MAX_PER_GROUP:
            lines.append(f"- … আরও {len(items) - MAX_PER_GROUP}টি (bounded report)")
        lines.append("")
    if len(lines) <= 4:
        lines.append("এই সময়ে কোনো কমিট নেই।")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate weekly changelog from git history"
    )
    parser.add_argument("--days", type=int, default=7)
    parser.add_argument("--output", default="CHANGELOG.auto.md")
    args = parser.parse_args()

    try:
        subjects = collect_subjects(args.days)
    except subprocess.CalledProcessError as exc:
        # বাংলা: git log ব্যর্থ = সৎ ব্যর্থতা (নীরব খালি ফাইল নয়)
        print(f"[changelog] git log failed: {exc.stderr}", file=sys.stderr)
        return 1

    output = render(group_subjects(subjects), args.days)
    out_path = args.output
    try:
        existing = ""
        try:
            with open(out_path, encoding="utf-8") as fh:
                existing = fh.read()
        except OSError:
            pass
        if existing != output:
            with open(out_path, "w", encoding="utf-8") as fh:
                fh.write(output)
            print(
                f"[changelog] updated {out_path} ({len(subjects)} commits in last {args.days}d)"
            )
        else:
            print(f"[changelog] no changes for {out_path}")
    except OSError as exc:
        print(f"[changelog] write failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
