#!/usr/bin/env python3
"""MCP Policy SSoT Generator (#2429) — schema → TS + Python embedded snapshots.

বাংলা মন্তব্য:
এই script-টি `config/mcp_policy_schema.json` (একমাত্র canonical উৎস) থেকে
দুটি embedded snapshot তৈরি করে:
  ১. infrastructure/mcp-control-plane/src/policy/policy.schema.generated.ts
  ২. backend/core/mcp_policy_schema_generated.py

ফলে TypeScript টাওয়ার ও Python ব্যাকএন্ডের পলিসি ইঞ্জিনের মধ্যে drift
অসম্ভব হয়ে যায় — দুই দিকই একই schema থেকে generated, হাতে লেখা ডুপ্লিকেট
নয়। রানটাইমে কোনো ফাইল I/O নেই (Free-tier constraint-friendly), snapshot
compile-এ embed হয়ে যায়।

Usage:
    python3 scripts/ci/generate_mcp_policy.py          # generate
    python3 scripts/ci/generate_mcp_policy.py --check  # শুধু drift check

Constitution Compliance:
  - Law #4 (Single Source of Truth): পলিসি একবারই define হয় — schema-তে
  - Law #19 (Observable): generated header-এ schema hash embed থাকে
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCHEMA_PATH = REPO_ROOT / "config" / "mcp_policy_schema.json"
TS_OUT = REPO_ROOT / "infrastructure" / "mcp-control-plane" / "src" / "policy" / "policy.schema.generated.ts"
PY_OUT = REPO_ROOT / "backend" / "core" / "mcp_policy_schema_generated.py"


def _schema_hash(schema: dict) -> str:
    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _render_ts(schema: dict, digest: str) -> str:
    """TS embedded snapshot — typed const, runtime import-free।"""
    provider_lines: list[str] = []
    for provider, rules in schema["providers"].items():
        entries = {k: v for k, v in rules.items() if k != "_default"}
        default = rules.get("_default")
        provider_lines.append(
            f"  {json.dumps(provider)}: {{ actions: {json.dumps(entries, ensure_ascii=False, indent=4).replace(chr(10), chr(10) + '  ')}"
            + (f", default: {json.dumps(default)}" if default is not None else "")
            + " },"
        )
    tool_map_lines = [
        f"  {json.dumps(tool)}: [{json.dumps(pa[0])}, {json.dumps(pa[1])}],"
        for tool, pa in schema["tool_provider_action"].items()
    ]
    return f"""// AUTO-GENERATED by scripts/ci/generate_mcp_policy.py — DO NOT EDIT BY HAND.
// বাংলা মন্তব্য: এই ফাইল config/mcp_policy_schema.json থেকে generated (#2429)।
// হাতে সম্পাদনা নিষিদ্ধ — schema বদলালে generator চালান।
// Canonical schema SHA-256 (prefix): {digest}

export interface PolicySchemaSnapshot {{
  schemaVersion: string;
  schemaHash: string;
  readOnlyProviders: string[];
  readOnlyKeywords: string[];
  defaultRisk: string;
  providers: Record<string, {{ actions: Record<string, string>; default?: string }}>;
  toolProviderAction: Record<string, [string, string]>;
  unknownToolMapping: [string, string];
  decisionMatrix: Record<string, string>;
}}

export const POLICY_SCHEMA: PolicySchemaSnapshot = {{
  schemaVersion: {json.dumps(schema["schema_version"])},
  schemaHash: {json.dumps(digest)},
  readOnlyProviders: {json.dumps(schema["read_only_providers"], ensure_ascii=False)},
  readOnlyKeywords: {json.dumps(schema["read_only_keywords"], ensure_ascii=False)},
  defaultRisk: {json.dumps(schema["default_risk"])},
  providers: {{
{chr(10).join("  " + line for line in provider_lines)}
  }},
  toolProviderAction: {{
{chr(10).join("  " + line for line in tool_map_lines)}
  }},
  unknownToolMapping: [{json.dumps(schema["unknown_tool_mapping"][0])}, {json.dumps(schema["unknown_tool_mapping"][1])}],
  decisionMatrix: {json.dumps(schema["decision_matrix"], ensure_ascii=False)},
}};
"""


def _render_py(schema: dict, digest: str) -> str:
    """Python embedded snapshot — dict literal, runtime import-free।"""
    providers_block: list[str] = []
    for provider, rules in schema["providers"].items():
        entries = {k: v for k, v in rules.items() if k != "_default"}
        default = rules.get("_default")
        providers_block.append(
            f"    {json.dumps(provider)}: {{\n"
            f"        \"actions\": {json.dumps(entries, ensure_ascii=False)},\n"
            + (f"        \"default\": {json.dumps(default)},\n" if default is not None else "")
            + "    },"
        )
    tool_map_lines = [
        f"    {json.dumps(tool)}: ({json.dumps(pa[0])}, {json.dumps(pa[1])}),"
        for tool, pa in schema["tool_provider_action"].items()
    ]
    return f'''# AUTO-GENERATED by scripts/ci/generate_mcp_policy.py — DO NOT EDIT BY HAND.
# বাংলা মন্তব্য: এই ফাইল config/mcp_policy_schema.json থেকে generated (#2429)।
# হাতে সম্পাদনা নিষিদ্ধ — schema বদলালে generator চালান।
# Canonical schema SHA-256 (prefix): {digest}

from __future__ import annotations

SCHEMA_VERSION = {json.dumps(schema["schema_version"])}
SCHEMA_HASH = {json.dumps(digest)}
READ_ONLY_PROVIDERS: tuple[str, ...] = {json.dumps(schema["read_only_providers"], ensure_ascii=False)}
READ_ONLY_KEYWORDS: tuple[str, ...] = {json.dumps(schema["read_only_keywords"], ensure_ascii=False)}
DEFAULT_RISK = {json.dumps(schema["default_risk"])}

# provider → (action → risk) টেবিল + optional per-provider default risk
PROVIDER_RULES: dict[str, dict[str, str]] = {{
{chr(10).join(providers_block)}
}}

# tool → (provider, action) mapping
TOOL_PROVIDER_ACTION: dict[str, tuple[str, str]] = {{
{chr(10).join(tool_map_lines)}
}}

UNKNOWN_TOOL_MAPPING: tuple[str, str] = ({json.dumps(schema["unknown_tool_mapping"][0])}, {json.dumps(schema["unknown_tool_mapping"][1])})

# risk level → policy decision
DECISION_MATRIX: dict[str, str] = {json.dumps(schema["decision_matrix"], ensure_ascii=False)}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="MCP Policy SSoT generator (#2429)")
    parser.add_argument("--check", action="store_true", help="শুধু drift check — ফাইল নতুন করে লেখে না")
    args = parser.parse_args()

    if not SCHEMA_PATH.exists():
        print(f"❌ schema পাওয়া যায়নি: {SCHEMA_PATH}", file=sys.stderr)
        return 2

    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    digest = _schema_hash(schema)
    ts_content = _render_ts(schema, digest)
    py_content = _render_py(schema, digest)

    if args.check:
        # বাংলা মন্তব্য: drift check — embedded snapshot গুলো কি এখনো schema-র
        # সাথে মিলে আছে? না মিললে exit 1 (CI gate হিসেবে ব্যবহারযোগ্য)।
        stale: list[str] = []
        if not TS_OUT.exists() or TS_OUT.read_text(encoding="utf-8") != ts_content:
            stale.append(str(TS_OUT.relative_to(REPO_ROOT)))
        if not PY_OUT.exists() or PY_OUT.read_text(encoding="utf-8") != py_content:
            stale.append(str(PY_OUT.relative_to(REPO_ROOT)))
        if stale:
            print("❌ MCP policy snapshot drift detected (schema → snapshot):")
            for path in stale:
                print(f"   - {path}")
            print("   চালান: python3 scripts/ci/generate_mcp_policy.py")
            return 1
        print(f"✅ MCP policy snapshots in sync (schema hash {digest})")
        return 0

    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text(ts_content, encoding="utf-8")
    PY_OUT.parent.mkdir(parents=True, exist_ok=True)
    PY_OUT.write_text(py_content, encoding="utf-8")
    print(f"✅ generated: {TS_OUT.relative_to(REPO_ROOT)}")
    print(f"✅ generated: {PY_OUT.relative_to(REPO_ROOT)}")
    print(f"   schema hash: {digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
