"""The complete error catalog.

This is the single source of truth for the error taxonomy shown in the
dashboard. It includes the user's original Bengali list PLUS the missed
categories we added (concurrency, typing, security, resources, deprecation,
logging) and the extra exceptions under each.

Used by:
  * `pyerrorfix catalog --format json` CLI command
  * The Next.js dashboard `/api/catalog` route
  * The documentation site
"""
from __future__ import annotations

from typing import Any

CATALOG: list[dict[str, Any]] = [
    {
        "id": "core-python",
        "name": "Core Python Errors",
        "name_bn": "কোর পাইথন এরর",
        "icon": "bug",
        "errors": [
            {"code": "SyntaxError", "title": "Syntax error",
             "description": "Grammar mistake or typo in the source code.",
             "description_bn": "কোডের ব্যাকরণগত ভুল বা টাইপো।",
             "severity": "error", "fixable": True, "rule_id": "syntax-error",
             "fix_strategy": "AST re-parse + targeted token correction"},
            {"code": "IndentationError", "title": "Indentation error",
             "description": "Wrong number of spaces/tabs at the start of a logical block.",
             "description_bn": "স্পেস বা ট্যাবের হিসেবে ভুল।",
             "severity": "error", "fixable": True, "rule_id": "indentation-error",
             "fix_strategy": "Re-indent to 4 spaces per level"},
            {"code": "TabError", "title": "Mixed tabs and spaces",
             "description": "Spaces and tabs mixed in the same indentation block.",
             "description_bn": "স্পেস এবং ট্যাব একসাথে মিলিয়ে ফেলা।",
             "severity": "error", "fixable": True, "rule_id": "tab-error",
             "fix_strategy": "Convert tabs to spaces"},
            {"code": "NameError", "title": "Undefined name",
             "description": "Using a variable or function before it is defined or imported.",
             "description_bn": "আনডিফাইনড ভেরিয়েবল বা ফাংশন কল করা।",
             "severity": "error", "fixable": False, "rule_id": "undefined-name",
             "fix_strategy": "Static scope analysis flags the missing definition"},
            {"code": "TypeError", "title": "Type mismatch",
             "description": "Operation applied to the wrong data type (e.g. str + int).",
             "description_bn": "ভুল ডেটা টাইপে অপারেশন (যেমন: স্ট্রিং + ইন্টিজার)।",
             "severity": "warning", "fixable": False, "rule_id": "type-mismatch",
             "fix_strategy": "Type-inference hints; recommend explicit casts"},
            {"code": "ValueError", "title": "Invalid value",
             "description": "Correct type but inappropriate value (e.g. int('x')).",
             "description_bn": "সঠিক টাইপ কিন্তু ভুল ভ্যালু ইনপুট দেওয়া।",
             "severity": "warning", "fixable": False, "rule_id": "possible-value-error",
             "fix_strategy": "Flag int()/float() on non-numeric literals"},
            {"code": "AttributeError", "title": "Missing attribute",
             "description": "Accessing a property/method that does not exist on the object.",
             "description_bn": "অবজেক্টের অস্তিত্বহীন কোনো প্রপার্টি বা মেথড কল করা।",
             "severity": "warning", "fixable": False, "rule_id": "missing-attribute",
             "fix_strategy": "Cross-reference known module/object members"},
            {"code": "IndexError", "title": "Index out of range",
             "description": "Accessing a list/tuple index beyond its bounds.",
             "description_bn": "লিস্ট বা টুপলের সীমানার বাইরের ইনডেক্স খোঁজা।",
             "severity": "warning", "fixable": False, "rule_id": "index-out-of-range",
             "fix_strategy": "Flag constant-index access on literals"},
            {"code": "KeyError", "title": "Missing dict key",
             "description": "Looking up a dictionary key that does not exist.",
             "description_bn": "ডিকশনারিতে এমন 'Key' খোঁজা যার অস্তিত্ব নেই।",
             "severity": "warning", "fixable": False, "rule_id": "missing-key",
             "fix_strategy": "Recommend dict.get(key, default)"},
            {"code": "UnboundLocalError", "title": "Local used before assignment",
             "description": "Reading a local variable before it is assigned in the function.",
             "description_bn": "লোকাল ভেরিয়েবলে ভ্যালু অ্যাসাইন করার আগেই ব্যবহার করা।",
             "severity": "error", "fixable": False, "rule_id": "unbound-local",
             "fix_strategy": "Lexical scope tracking of assignments vs reads"},
            {"code": "ZeroDivisionError", "title": "Division by zero",
             "description": "Dividing or modulo by zero.",
             "description_bn": "কোনো সংখ্যাকে শূন্য (0) দিয়ে ভাগ করার চেষ্টা।",
             "severity": "error", "fixable": False, "rule_id": "zero-division",
             "fix_strategy": "Flag division by a provably-zero literal"},
            {"code": "NotImplementedError", "title": "Unimplemented abstract stub",
             "description": "Method inherited but never implemented in the subclass.",
             "description_bn": "ইনহেরিট করা ক্লাসে মেথড তৈরি না করা।",
             "severity": "warning", "fixable": False, "rule_id": "not-implemented-stub",
             "fix_strategy": "Flag raise NotImplementedError in non-abstract methods"},
            {"code": "RecursionError", "title": "Recursion limit exceeded",
             "description": "A function calls itself indefinitely, hitting the recursion limit.",
             "description_bn": "লুপ বা রিকার্শন লিমিট পার হয়ে যাওয়া।",
             "severity": "warning", "fixable": False, "rule_id": "deep-recursion",
             "fix_strategy": "Detect unconditional self-calls; suggest iteration"},
            {"code": "MemoryError", "title": "Out of memory",
             "description": "Program exhausted available RAM.",
             "description_bn": "প্রোগ্রামের কারণে র‍্যাম (RAM) ফুল হয়ে যাওয়া।",
             "severity": "error", "fixable": False, "rule_id": "overflow-risk",
             "fix_strategy": "Flag unbounded list comprehensions / huge literals"},
            {"code": "AssertionError", "title": "Assertion failure",
             "description": "assert statement failed (stripped under python -O).",
             "description_bn": "assert ব্যবহার করলে এটি -O ফ্ল্যাগে কাজ করে না।",
             "severity": "warning", "fixable": True, "rule_id": "assert-in-prod",
             "fix_strategy": "Convert assert to explicit raise ValueError"},
            {"code": "OverflowError", "title": "Numeric overflow",
             "description": "Result too large to represent (e.g. float of huge int).",
             "description_bn": "সংখ্যার মান টাইপের সীমা ছাড়িয়ে গেছে।",
             "severity": "warning", "fixable": False, "rule_id": "overflow-risk",
             "fix_strategy": "Flag >4300-digit integer literals"},
            {"code": "StopIteration", "title": "StopIteration in generator (PEP 479)",
             "description": "Raising StopIteration inside a generator became a RuntimeError (PEP 479).",
             "description_bn": "জেনারেটরের ভেতরে StopIteration রেইজ করলে এখন RuntimeError হয়।",
             "severity": "info", "fixable": False, "rule_id": "stop-iteration-explicit",
             "fix_strategy": "Replace `raise StopIteration` with `return`"},
            {"code": "RuntimeError", "title": "Bare raise outside except",
             "description": "`raise` with no active exception is a RuntimeError.",
             "description_bn": "except ব্লকের বাইরে খালি raise ব্যবহার করলে RuntimeError হয়।",
             "severity": "warning", "fixable": False, "rule_id": "bare-raise",
             "fix_strategy": "Restrict bare raise to except blocks"},
        ],
    },
    {
        "id": "imports",
        "name": "Import & Module Errors",
        "name_bn": "ইমপোর্ট ও মডিউল এরর",
        "icon": "package",
        "errors": [
            {"code": "ModuleNotFoundError", "title": "Module not installed",
             "description": "Module/package is not installed (pip install missing).",
             "description_bn": "মডিউল বা প্যাকেজ ইন্সটল না থাকা (যেমন pip install করতে ভুলে যাওয়া)।",
             "severity": "error", "fixable": False, "rule_id": "missing-module",
             "fix_strategy": "Cross-reference against stdlib + installed packages"},
            {"code": "ImportError", "title": "Name import failure / circular import",
             "description": "from module import Name fails, or circular import detected.",
             "description_bn": "মডিউল থেকে কোনো ফাংশন ইমপোর্টে ব্যর্থতা বা সার্কুলার ইমপোর্ট ইস্যু।",
             "severity": "error", "fixable": False, "rule_id": "missing-name-import",
             "fix_strategy": "Introspect stdlib module attrs at scan time"},
            {"code": "ImportError", "title": "Circular import risk",
             "description": "Module A imports B which imports A back — ImportError on startup.",
             "description_bn": "A, B কে import করে আর B, A কে — সার্কুলার ইমপোর্ট।",
             "severity": "warning", "fixable": False, "rule_id": "circular-import-risk",
             "fix_strategy": "File-path-based cycle heuristic"},
            {"code": "ImportError", "title": "Wildcard import",
             "description": "from x import * pollutes the namespace.",
             "description_bn": "import * নেমস্পেস দূষিত করে।",
             "severity": "warning", "fixable": True, "rule_id": "wildcard-import",
             "fix_strategy": "Replace * with explicit names"},
            {"code": "ImportError", "title": "Unused import",
             "description": "Imported name never referenced — dead weight, slows startup.",
             "description_bn": "ইমপোর্ট করা হলো কিন্তু কখনো ব্যবহার হয়নি।",
             "severity": "warning", "fixable": True, "rule_id": "unused-import",
             "fix_strategy": "Auto-remove the import line"},
        ],
    },
    {
        "id": "files",
        "name": "File & OS Errors",
        "name_bn": "ফাইল ও অপারেটিং সিস্টেম এরর",
        "icon": "folder",
        "errors": [
            {"code": "FileNotFoundError", "title": "File not found",
             "description": "The file referenced in code does not exist on disk.",
             "description_bn": "কোডে উল্লেখিত ফাইলটি হার্ডড্রাইভে খুঁজে না পাওয়া।",
             "severity": "warning", "fixable": True, "rule_id": "missing-path-exists-check",
             "fix_strategy": "Wrap open() in try/except or check Path.exists()"},
            {"code": "PermissionError", "title": "Permission denied",
             "description": "No read/write permission on the file.",
             "description_bn": "ফাইল রিড/রাইট করার পারমিশন না থাকা।",
             "severity": "warning", "fixable": False, "rule_id": "hardcoded-path",
             "fix_strategy": "Flag writes to system paths"},
            {"code": "TimeoutError", "title": "Operation timed out",
             "description": "System or network operation exceeded the allotted time.",
             "description_bn": "সিস্টেম বা নেটওয়ার্ক অপারেশনে নির্ধারিত সময়ের চেয়ে বেশি সময় লাগা।",
             "severity": "warning", "fixable": False, "rule_id": "broad-except-io",
             "fix_strategy": "Recommend explicit timeout= args"},
            {"code": "EOFError", "title": "Unexpected end of input",
             "description": "Reached end-of-file unexpectedly while reading.",
             "description_bn": "ফাইলের শেষে (End of File) অপ্রত্যাশিতভাবে পৌঁছে যাওয়া।",
             "severity": "warning", "fixable": False, "rule_id": "broad-except-io",
             "fix_strategy": "Validate input length before read"},
            {"code": "IsADirectoryError", "title": "Path is a directory",
             "description": "open() called on a directory (added — was missed).",
             "description_bn": "open() ডিরেক্টরির উপর কল করা হয়েছে (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "missing-path-exists-check",
             "fix_strategy": "Check Path.is_dir() before open()"},
            {"code": "NotADirectoryError", "title": "Path is not a directory",
             "description": "Directory operation on a file path (added — was missed).",
             "description_bn": "ফাইলের উপর ডিরেক্টরি অপারেশন (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "missing-path-exists-check",
             "fix_strategy": "Check Path.is_dir()"},
            {"code": "BlockingIOError", "title": "Non-blocking I/O would block",
             "description": "Non-blocking read/write would block (added — was missed).",
             "description_bn": "নন-ব্লকিং I/O এ ব্লক হতে চলেছে (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "broad-except-io",
             "fix_strategy": "Retry with select/epoll"},
        ],
    },
    {
        "id": "asyncio",
        "name": "Asyncio Errors",
        "name_bn": "এসিনক্রোনাস এরর",
        "icon": "zap",
        "errors": [
            {"code": "RuntimeWarning", "title": "coroutine was never awaited",
             "description": "Async function called without `await` — coroutine discarded.",
             "description_bn": "Async ফাংশন কল করার সময় await দিতে ভুলে যাওয়া।",
             "severity": "error", "fixable": True, "rule_id": "missing-await",
             "fix_strategy": "Auto-insert `await` before the call"},
            {"code": "CancelledError", "title": "Task cancelled",
             "description": "An async task was cancelled while running.",
             "description_bn": "কোনো Async টাস্ক চলাকালীন সেটি বাতিল হয়ে যাওয়া।",
             "severity": "warning", "fixable": False, "rule_id": "blocking-call-in-async",
             "fix_strategy": "Flag blocking calls that starve the loop"},
            {"code": "InvalidStateError", "title": "Invalid task state",
             "description": "Operating on a task/future in the wrong state.",
             "description_bn": "কোনো টাস্কের ভুল স্টেটে অপারেশন চালানো।",
             "severity": "warning", "fixable": False, "rule_id": "unhandled-task-exception",
             "fix_strategy": "Keep task references and await them"},
            {"code": "RuntimeError", "title": "No running event loop",
             "description": "asyncio.get_event_loop() / run() misuse (added — was missed).",
             "description_bn": "ইভেন্ট লুপ ছাড়া async অপারেশন (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "event-loop-misuse",
             "fix_strategy": "Use asyncio.run() / get_running_loop()"},
            {"code": "RuntimeError", "title": "Unhandled task exception",
             "description": "create_task() whose exception is never retrieved (added).",
             "description_bn": "create_task() এর এক্সেপশন কখনো নেওয়া হয়নি (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "unhandled-task-exception",
             "fix_strategy": "Keep task reference; await / add_done_callback"},
        ],
    },
    {
        "id": "database",
        "name": "Database & ORM Errors",
        "name_bn": "ডাটাবেস ও SQLAlchemy এরর",
        "icon": "database",
        "errors": [
            {"code": "IntegrityError", "title": "Constraint violation",
             "description": "Duplicate unique key, FK violation, NOT NULL breach.",
             "description_bn": "ডেটাবেসের নিয়ম ভাঙা (যেমন: ডুপ্লিকেট Unique Key ইনসার্ট করা)।",
             "severity": "warning", "fixable": False, "rule_id": "raw-sql-injection",
             "fix_strategy": "Recommend ON CONFLICT / upsert patterns"},
            {"code": "OperationalError", "title": "Connection / server failure",
             "description": "DB connection failed or server is down.",
             "description_bn": "ডাটাবেস কানেকশন ফেইল করা বা সার্ভার ডাউন থাকা।",
             "severity": "warning", "fixable": False, "rule_id": "n-plus-one-query",
             "fix_strategy": "Flag connection lifecycle issues"},
            {"code": "ProgrammingError", "title": "Bad SQL / missing table",
             "description": "Wrong SQL syntax or table does not exist.",
             "description_bn": "ভুল SQL সিনট্যাক্স বা টেবিলের অস্তিত্ব না থাকা।",
             "severity": "warning", "fixable": False, "rule_id": "missing-noresult-found",
             "fix_strategy": "Validate table names against schema"},
            {"code": "DataError", "title": "Value too large / wrong format",
             "description": "Inserting data that exceeds column limits.",
             "description_bn": "ভুল ডেটা ইনসার্ট করা (যেমন: লিমিটের চেয়ে বেশি ক্যারেক্টার দেওয়া)।",
             "severity": "warning", "fixable": False, "rule_id": "raw-sql-injection",
             "fix_strategy": "Validate length before insert"},
            {"code": "StatementError", "title": "SQL injection / bad bind",
             "description": "f-string or concatenation in SQL — injection + bind error.",
             "description_bn": "SQL-এ f-string — ইনজেকশন ও বাইন্ড এরর উভয়ই।",
             "severity": "critical", "fixable": False, "rule_id": "raw-sql-injection",
             "fix_strategy": "Flag text()/execute() with dynamic strings"},
            {"code": "NoResultFound", "title": "query.one() on empty result (added)",
             "description": "query.one() raises when no row — was missed in original list.",
             "description_bn": "query.one() ফলাফল না পেলে NoResultFound রেইজ করে (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "missing-noresult-found",
             "fix_strategy": "Recommend .one_or_none() / try-except"},
            {"code": "MultipleResultsFound", "title": "query.one() on many (added)",
             "description": "query.one() raises when more than one row — was missed.",
             "description_bn": "query.one() একাধিক ফলাফলে MultipleResultsFound (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "missing-noresult-found",
             "fix_strategy": "Use .first() / .one_or_none()"},
        ],
    },
    {
        "id": "web-api",
        "name": "Web & API Errors",
        "name_bn": "ওয়েব ও API এরর",
        "icon": "globe",
        "errors": [
            {"code": "ValidationError", "title": "Pydantic validation failed",
             "description": "Incoming data type/format doesn't match the Pydantic schema.",
             "description_bn": "API-তে আসা ডেটার টাইপ বা ফরম্যাট Pydantic স্কিমার সাথে না মেলা।",
             "severity": "warning", "fixable": True, "rule_id": "pydantic-validation-gap",
             "fix_strategy": "Replace .dict() → .model_dump() (v2)"},
            {"code": "HTTPException", "title": "Manually raised client error",
             "description": "Manually thrown client error (404/401).",
             "description_bn": "ম্যানুয়ালি থ্রো করা ক্লায়েন্ট এরর (যেমন: 404 Not Found বা 401 Unauthorized)।",
             "severity": "info", "fixable": False, "rule_id": "broad-http-exception",
             "fix_strategy": "Don't raise 5xx manually; let the framework handle it"},
            {"code": "RequestValidationError", "title": "Request body invalid (added)",
             "description": "FastAPI request body failed validation (was missed).",
             "description_bn": "FastAPI রিকোয়েস্ট বডি ভ্যালিডেশনে ব্যর্থ (নতুন যোগ)।",
             "severity": "warning", "fixable": False, "rule_id": "pydantic-validation-gap",
             "fix_strategy": "Add response_model + strict Pydantic schemas"},
            {"code": "SerializationError", "title": "Response serialization (added)",
             "description": "Route returns a type that can't be serialized (was missed).",
             "description_bn": "রাউট এমন টাইপ রিটার্ন করছে যা serialize হয় না (নতুন যোগ)।",
             "severity": "info", "fixable": False, "rule_id": "missing-response-model",
             "fix_strategy": "Add response_model=Model to routes"},
        ],
    },
    {
        "id": "concurrency",
        "name": "Concurrency Errors (NEW)",
        "name_bn": "কনকারেন্সি এরর (নতুন)",
        "icon": "git-branch",
        "errors": [
            {"code": "RuntimeError", "title": "Mutable shared state",
             "description": "Module-level mutable global mutated from async/threaded code without a lock.",
             "description_bn": "মডিউল-লেভেল মিউটেবল গ্লোবাল লক ছাড়া মিউটেট করা হচ্ছে।",
             "severity": "warning", "fixable": False, "rule_id": "mutable-shared-state",
             "fix_strategy": "Guard with a lock or move to per-task state"},
            {"code": "RuntimeError", "title": "Lock without context manager",
             "description": "lock.acquire() without `with` — deadlock if exception skips release.",
             "description_bn": "lock.acquire() without `with` — ডেডলক ঝুঁকি।",
             "severity": "warning", "fixable": True, "rule_id": "lock-without-context",
             "fix_strategy": "Use `with lock:`"},
            {"code": "RuntimeError", "title": "Thread-unsafe singleton",
             "description": "Global instance created at import and shared across workers.",
             "description_bn": "গ্লোবাল ইনস্ট্যান্স ওয়ার্কারে শেয়ার হচ্ছে।",
             "severity": "warning", "fixable": False, "rule_id": "thread-unsafe-singleton",
             "fix_strategy": "Use a lock-guarded factory or per-worker instance"},
        ],
    },
    {
        "id": "typing",
        "name": "Typing Errors (NEW)",
        "name_bn": "টাইপিং এরর (নতুন)",
        "icon": "type",
        "errors": [
            {"code": "AttributeError", "title": "NoneType member access",
             "description": "Attribute access on a value that may be None (Optional/.get()/.first()).",
             "description_bn": "Optional ভ্যালুর উপর অ্যাট্রিবিউট অ্যাক্সেস।",
             "severity": "warning", "fixable": False, "rule_id": "none-member-access",
             "fix_strategy": "Guard with `if var is not None:`"},
            {"code": "TypeError", "title": "Optional used without None check",
             "description": "Function parameter is Optional but no None-check in body.",
             "description_bn": "প্যারামিটার Optional কিন্তু None চেক নেই।",
             "severity": "warning", "fixable": False, "rule_id": "optional-without-check",
             "fix_strategy": "Add `if param is None:` guard"},
            {"code": "TypeError", "title": "Missing type hint",
             "description": "Public function has no return annotation.",
             "description_bn": "পাবলিক ফাংশনে রিটার্ন টাইপ অ্যানোটেশন নেই।",
             "severity": "info", "fixable": False, "rule_id": "missing-type-hint",
             "fix_strategy": "Add return type annotation"},
        ],
    },
    {
        "id": "security",
        "name": "Security Errors (NEW)",
        "name_bn": "সিকিউরিটি এরর (নতুন)",
        "icon": "shield",
        "errors": [
            {"code": "ValueError", "title": "Hardcoded secret",
             "description": "API key/password/token assigned as a string literal.",
             "description_bn": "সিক্রেট/পাসওয়ার্ড হার্ডকোড করা।",
             "severity": "critical", "fixable": True, "rule_id": "hardcoded-secret",
             "fix_strategy": "Read from environment variable"},
            {"code": "RuntimeError", "title": "eval() / exec()",
             "description": "Arbitrary code execution — RCE vector.",
             "description_bn": "eval/exec — রিমোট কোড এক্সিকিউশন।",
             "severity": "critical", "fixable": False, "rule_id": "eval-exec",
             "fix_strategy": "Use ast.literal_eval for literals"},
            {"code": "RuntimeError", "title": "Unsafe deserialization",
             "description": "pickle.loads / yaml.load on untrusted input — RCE.",
             "description_bn": "pickle/yaml.load — আনট্রাস্টেড ইনপুটে RCE।",
             "severity": "error", "fixable": False, "rule_id": "pickle-deserialize",
             "fix_strategy": "Use yaml.safe_load / json.loads"},
            {"code": "RuntimeError", "title": "Shell injection",
             "description": "subprocess(shell=True) with a dynamic command.",
             "description_bn": "subprocess(shell=True) ডায়নামিক কমান্ডে।",
             "severity": "critical", "fixable": False, "rule_id": "shell-injection",
             "fix_strategy": "Pass args as a list, shell=False"},
            {"code": "ValueError", "title": "Weak hash",
             "description": "hashlib.md5/sha1 used for security.",
             "description_bn": "md5/sha1 সিকিউরিটিতে ব্যবহার।",
             "severity": "warning", "fixable": False, "rule_id": "weak-hash",
             "fix_strategy": "Use sha256 / bcrypt / passlib"},
        ],
    },
    {
        "id": "resources",
        "name": "Resource Leak Errors (NEW)",
        "name_bn": "রিসোর্স লিক এরর (নতুন)",
        "icon": "droplet",
        "errors": [
            {"code": "ResourceWarning", "title": "Unclosed resource",
             "description": "open()/socket()/engine created without `with` or .close().",
             "description_bn": "open/socket/engine `with` ছাড়া তৈরি।",
             "severity": "warning", "fixable": True, "rule_id": "unclosed-resource",
             "fix_strategy": "Use context manager"},
            {"code": "ResourceWarning", "title": "Leaked DB connection",
             "description": "Connection/Session not closed in finally.",
             "description_bn": "কানেকশন/সেশন finally-তে ক্লোজ হয়নি।",
             "severity": "warning", "fixable": False, "rule_id": "leaked-connection",
             "fix_strategy": "Close in finally / use context manager"},
        ],
    },
    {
        "id": "deprecation",
        "name": "Deprecation Errors (NEW)",
        "name_bn": "ডেপ্রিকেশন এরর (নতুন)",
        "icon": "archive",
        "errors": [
            {"code": "AttributeError", "title": "Removed API",
             "description": "imp.*, distutils.*, cgi.* removed in 3.12+.",
             "description_bn": "imp/distutils/cgi ৩.১২+ এ সরানো হয়েছে।",
             "severity": "warning", "fixable": False, "rule_id": "deprecated-api",
             "fix_strategy": "Migrate to importlib / packaging"},
            {"code": "AttributeError", "title": "Moved stdlib name",
             "description": "collections.Callable → collections.abc.Callable etc.",
             "description_bn": "collections.Callable → collections.abc.Callable।",
             "severity": "warning", "fixable": False, "rule_id": "deprecated-api",
             "fix_strategy": "Use the collections.abc submodule"},
            {"code": "AttributeError", "title": "Python 2 construct",
             "description": "xrange/unicode/print >> — removed in Python 3.",
             "description_bn": "xrange/unicode/print >> — পাইথন ৩-এ সরানো।",
             "severity": "warning", "fixable": False, "rule_id": "python2-construct",
             "fix_strategy": "Use range/str/print()"},
        ],
    },
    {
        "id": "logging",
        "name": "Logging & Exception Errors (NEW)",
        "name_bn": "লগিং ও এক্সেপশন এরর (নতুন)",
        "icon": "file-text",
        "errors": [
            {"code": "RuntimeWarning", "title": "f-string in logging",
             "description": "logger.info(f'...') formats eagerly even when level is off.",
             "description_bn": "logger.info(f'...') সবসময় ফরম্যাট করে।",
             "severity": "warning", "fixable": True, "rule_id": "fstring-in-logging",
             "fix_strategy": "Convert to lazy %-style args"},
            {"code": "Exception", "title": "Broad except",
             "description": "Bare except: or except Exception: swallowing errors.",
             "description_bn": "ব্রড except এরর ঢেকে রাখে।",
             "severity": "warning", "fixable": True, "rule_id": "broad-except",
             "fix_strategy": "Narrow the exception type or re-raise after logging"},
            {"code": "RuntimeError", "title": "raise without `from`",
             "description": "raise inside except loses the cause chain.",
             "description_bn": "except-এর ভেতরে raise কজ চেইন হারায়।",
             "severity": "info", "fixable": True, "rule_id": "exception-not-logged",
             "fix_strategy": "Add `from err`"},
            {"code": "RuntimeWarning", "title": "print() in production",
             "description": "print() bypasses the logging framework.",
             "description_bn": "print() লগিং ফ্রেমওয়ার্ক বাইপাস করে।",
             "severity": "info", "fixable": False, "rule_id": "print-in-production",
             "fix_strategy": "Replace with logger.info()"},
        ],
    },
    # ─────────────────────────────────────────────────────────────────────────
    # NEW categories from the expanded 11-category taxonomy (user's 2nd message)
    # ─────────────────────────────────────────────────────────────────────────
    {
        "id": "network-io",
        "name": "Network & I/O Errors (NEW)",
        "name_bn": "নেটওয়ার্ক ও I/O এরর (নতুন)",
        "icon": "wifi",
        "errors": [
            {"code": "ConnectionRefusedError", "title": "Connection refused",
             "description": "Server actively refused the connection (not running / wrong port).",
             "description_bn": "সার্ভার থেকে কানেকশন রিজেক্ট করা।",
             "severity": "warning", "fixable": False, "rule_id": "uncaught-connection-error",
             "fix_strategy": "Wrap socket.connect in try/except OSError; retry with backoff"},
            {"code": "ConnectionResetError", "title": "Connection reset by peer",
             "description": "Connection dropped mid-stream (peer crashed / network blip).",
             "description_bn": "মাঝপথে কানেকশন কেটে যাওয়া।",
             "severity": "warning", "fixable": False, "rule_id": "uncaught-connection-error",
             "fix_strategy": "Wrap in try/except ConnectionError; retry idempotent requests"},
            {"code": "TimeoutError", "title": "Network call without timeout",
             "description": "requests/httpx/socket call with no timeout= — blocks forever on hung peer.",
             "description_bn": "নির্ধারিত সময়ের মধ্যে রেসপন্স না পাওয়া (timeout= ছাড়া)।",
             "severity": "warning", "fixable": True, "rule_id": "missing-timeout",
             "fix_strategy": "Add timeout=10 (or (connect, read) tuple)"},
            {"code": "ReadTimeout", "title": "Read timeout",
             "description": "Third-party server too slow to respond.",
             "description_bn": "থার্ড-পার্টি সার্ভার অনেক স্লো হলে।",
             "severity": "warning", "fixable": False, "rule_id": "missing-timeout",
             "fix_strategy": "Set per-call timeout + retry with jitter"},
            {"code": "ConnectTimeout", "title": "Connect timeout",
             "description": "Cannot establish TCP connection in time.",
             "description_bn": "কানেকশন স্থাপনে সময় শেষ।",
             "severity": "warning", "fixable": False, "rule_id": "missing-timeout",
             "fix_strategy": "Use (connect_timeout, read_timeout) tuple"},
            {"code": "JSONDecodeError", "title": "json.loads without try",
             "description": "Third-party API returns HTML/empty body → JSONDecodeError.",
             "description_bn": "এক্সটার্নাল API থেকে আসা রেসপন্স সঠিক JSON না হলে।",
             "severity": "warning", "fixable": False, "rule_id": "json-decode-uncaught",
             "fix_strategy": "Wrap json.loads in try/except json.JSONDecodeError"},
            {"code": "FileExistsError", "title": "File already exists (NEW)",
             "description": "open(path, 'x') — file already exists.",
             "description_bn": "একই নামের ফাইল আগে থেকেই থাকা।",
             "severity": "warning", "fixable": False, "rule_id": "hardcoded-path",
             "fix_strategy": "Use mode='x' and handle FileExistsError, or check Path.exists()"},
        ],
    },
    {
        "id": "linter-quality",
        "name": "Linter & Code-Quality Errors (NEW)",
        "name_bn": "লিন্টার ও কোড কোয়ালিটি এরর (নতুন)",
        "icon": "code",
        "errors": [
            {"code": "B905", "title": "zip() without strict=",
             "description": "zip() silently truncates to the shortest iterable (Flake8-Bugbear B905).",
             "description_bn": "zip() ফাংশনে strict প্যারামিটার ব্যবহার না করা।",
             "severity": "warning", "fixable": True, "rule_id": "zip-without-strict",
             "fix_strategy": "Add strict=True"},
            {"code": "E712", "title": "Comparison to bool literal",
             "description": "x == True / x == False (Pycodestyle E712).",
             "description_bn": "বুলিয়ান ভ্যালুর সাথে == বা != ব্যবহার করা।",
             "severity": "warning", "fixable": True, "rule_id": "bool-compare-literal",
             "fix_strategy": "Replace `x == True` with `if x:`"},
            {"code": "E722", "title": "Bare except:",
             "description": "except: with no exception type (Pycodestyle E722).",
             "description_bn": "try-except-এ নির্দিষ্ট এররের নাম উল্লেখ না করে শুধু except: লেখা।",
             "severity": "warning", "fixable": True, "rule_id": "broad-except",
             "fix_strategy": "Use `except Exception:` at minimum"},
            {"code": "C901", "title": "Deeply nested if/else",
             "description": "Too many nested if/else blocks — high cognitive complexity.",
             "description_bn": "অতিরিক্ত Nested if-else ব্যবহার করে কোড জটিল করা।",
             "severity": "info", "fixable": False, "rule_id": "nested-if-style",
             "fix_strategy": "Use guard clauses / early returns to flatten"},
            {"code": "SIM108", "title": "Verbose if/else (use ternary)",
             "description": "if/else assigning the same name — should be a ternary.",
             "description_bn": "যেখানে টার্নারি ব্যবহার করা যেত, সেখানে বড় if-else।",
             "severity": "info", "fixable": True, "rule_id": "ternary-style",
             "fix_strategy": "Collapse into `x = a if cond else b`"},
            {"code": "F841", "title": "Dead mock (created, never used)",
             "description": "unittest.mock created but never asserted on.",
             "description_bn": "ইউনিট টেস্টে Mock তৈরি করা হলো কিন্তু ব্যবহার না হওয়া।",
             "severity": "warning", "fixable": True, "rule_id": "dead-mock",
             "fix_strategy": "Remove the mock or add .assert_called_once()"},
            {"code": "N816", "title": "Naming convention mismatch",
             "description": "snake_case var assigned camelCase external API attribute.",
             "description_bn": "snake_case ও camelCase-এর মধ্যে সামঞ্জস্য না রাখা।",
             "severity": "info", "fixable": False, "rule_id": "naming-convention-mismatch",
             "fix_strategy": "Document the mapping or normalise with a snake_case alias"},
        ],
    },
    {
        "id": "auth-security",
        "name": "Security & Authentication Errors (NEW)",
        "name_bn": "সিকিউরিটি ও অথেনটিকেশন এরর (নতুন)",
        "icon": "lock",
        "errors": [
            {"code": "InvalidTokenError", "title": "JWT without signature verification",
             "description": "jwt.decode with verify_signature=False — accepts forged tokens.",
             "description_bn": "JWT টোকেন ভেরিফাই না করে ডিকোড করা।",
             "severity": "critical", "fixable": False, "rule_id": "jwt-unverified",
             "fix_strategy": "Remove options={'verify_signature': False}; pass the real key"},
            {"code": "ExpiredSignatureError", "title": "JWT expiry not checked",
             "description": "Missing algorithms= → 'none' alg / expiry skipped on older jwt libs.",
             "description_bn": "ইউজারের JWT বা সেশন টোকেনের মেয়াদ শেষ হয়ে গেলে।",
             "severity": "warning", "fixable": True, "rule_id": "jwt-missing-algorithms",
             "fix_strategy": "Pass algorithms=['HS256'] (or your actual algorithm)"},
            {"code": "RuntimeError", "title": "CORS allow_origins=['*'] + credentials",
             "description": "Wildcard origin + credentials = authenticated cross-site reads.",
             "description_bn": "CORS wildcard + credentials — ব্রাউজার রিজেক্ট করে, আর সার্ভার অনুমতি দিলে লিক।",
             "severity": "critical", "fixable": False, "rule_id": "cors-wildcard-credentials",
             "fix_strategy": "Set explicit allow_origins list OR allow_credentials=False"},
            {"code": "RuntimeError", "title": "CORS wildcard origin",
             "description": "allow_origins=['*'] lets any website call your API.",
             "description_bn": "যেকোনো ওয়েবসাইট থেকে API কল অনুমোদন।",
             "severity": "warning", "fixable": False, "rule_id": "cors-wildcard",
             "fix_strategy": "Restrict to your real frontend origins"},
            {"code": "HTTPException", "title": "Manual 401/403 (use Depends)",
             "description": "Hardcoded raise HTTPException(401/403) bypassing DI auth.",
             "description_bn": "ইউজারের লগইন না থাকলে 401/403 — কিন্তু Depends ছাড়া ম্যানুয়ালি।",
             "severity": "info", "fixable": False, "rule_id": "manual-auth-gate",
             "fix_strategy": "Use Depends(get_current_user) on the route"},
        ],
    },
    {
        "id": "testing",
        "name": "Testing & Assertion Errors (NEW)",
        "name_bn": "টেস্টিং ও অ্যাসারশন এরর (নতুন)",
        "icon": "flask-conical",
        "errors": [
            {"code": "AssertionError", "title": "assert without message",
             "description": "Bare `assert x` shows only AssertionError on failure.",
             "description_bn": "assert-এ মেসেজ না থাকলে ডিবাগ কঠিন।",
             "severity": "info", "fixable": True, "rule_id": "assert-without-message",
             "fix_strategy": "Add `assert x, 'expected ...'`"},
            {"code": "FixtureLookupError", "title": "Session fixture mutates state",
             "description": "scope='session' fixture mutates shared state → flaky tests.",
             "description_bn": "সেশন ফিক্সচার স্টেট মিউটেট করলে টেস্ট পলিউশন।",
             "severity": "warning", "fixable": False, "rule_id": "session-fixture-mutation",
             "fix_strategy": "Use scope='function' or return immutable data"},
            {"code": "AssertionError", "title": "pytest.raises without match=",
             "description": "Catches ANY exception of the type, even the wrong one.",
             "description_bn": "pytest.raises-এ match= না থাকলে ভুল এররও ধরা যায়।",
             "severity": "info", "fixable": True, "rule_id": "pytest.raises-without-match",
             "fix_strategy": "Add match='expected message substring'"},
        ],
    },
    {
        "id": "infra-deploy",
        "name": "Infrastructure & Deployment Errors (NEW)",
        "name_bn": "ইনফ্রাস্ট্রাকচার ও ডেপ্লয়মেন্ট এরর (নতুন)",
        "icon": "server",
        "errors": [
            {"code": "OOMKilled", "title": "Docker no memory limit",
             "description": "Container without mem_limit → OOM-killed (exit 137) on leak.",
             "description_bn": "ডকার কনটেইনারের RAM ফুল হলে Linux OOM-killer প্রোগ্রাম কিল করে (exit 137)।",
             "severity": "warning", "fixable": True, "rule_id": "docker-no-memory-limit",
             "fix_strategy": "Add mem_limit: 512m (compose) or --memory=512m (run)"},
            {"code": "502", "title": "Docker image without HEALTHCHECK",
             "description": "Orchestrator can't detect hung process → 502 before unhealthy.",
             "description_bn": "HEALTHCHECK না থাকলে হ্যাং করা প্রসেস ধরা যায় না → 502।",
             "severity": "info", "fixable": True, "rule_id": "docker-missing-healthcheck",
             "fix_strategy": "Add HEALTHCHECK CMD curl -f http://localhost:8000/health || exit 1"},
            {"code": "502", "title": "Docker runs as root",
             "description": "No USER directive → container runs as root (escape = host root).",
             "description_bn": "কনটেইনার root হিসেবে চললে এস্কেপ = হোস্ট root।",
             "severity": "warning", "fixable": True, "rule_id": "docker-root-user",
             "fix_strategy": "Add `USER appuser` after creating a non-root user"},
            {"code": "502", "title": "gunicorn without --workers",
             "description": "Defaults to 1 worker → 502 under load.",
             "description_bn": "গানিকর্ন ডিফল্ট ১ ওয়ার্কার → লোডে 502।",
             "severity": "warning", "fixable": True, "rule_id": "gunicorn-missing-workers",
             "fix_strategy": "Add --workers 4 (recommendation: 2*CPU+1)"},
            {"code": "504", "title": "nginx without proxy_read_timeout",
             "description": "Default 60s → 504 on long queries.",
             "description_bn": "nginx ডিফল্ট ৬০s → ভারী কোয়েরিতে 504।",
             "severity": "warning", "fixable": True, "rule_id": "nginx-missing-proxy-timeout",
             "fix_strategy": "Add `proxy_read_timeout 300s;` to the location"},
            {"code": "502", "title": "nginx proxy_pass to wrong port",
             "description": "proxy_pass to 127.0.0.1:80 forwards to nginx itself → 502.",
             "description_bn": "nginx নিজের পোর্টে ফরওয়ার্ড → 502।",
             "severity": "warning", "fixable": True, "rule_id": "nginx-wrong-backend-port",
             "fix_strategy": "Use the backend's real port (8000/8080)"},
        ],
    },
]


def catalog_summary() -> dict[str, Any]:
    """Counts per category for the dashboard header."""
    return {
        "categories": len(CATALOG),
        "errors": sum(len(c["errors"]) for c in CATALOG),
        "fixable": sum(1 for c in CATALOG for e in c["errors"] if e["fixable"]),
    }
