"""create_system_config

Revision ID: ed9761fee64f
Revises: 664fe16e33ca
Create Date: 2026-07-08 02:54:58.952639

"""

from collections.abc import Sequence

# ruff: noqa: I001
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed9761fee64f"
down_revision: str | Sequence[str] | None = "664fe16e33ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("system_config", sa.Column("id", sa.UUID(), nullable=True))
    op.add_column("system_config", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("system_config", sa.Column("version", sa.Integer(), nullable=True))
    op.add_column(
        "system_config",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    # SAFE FIX: alter_column from TEXT to VARCHAR is generally safe when
    # shortening (existing data fits in the new length), but we use
    # USING clause to ensure data is cast properly.
    op.alter_column(
        "system_config",
        "key",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
        postgresql_using="key::varchar(255)",
    )
    op.alter_column(
        "system_config",
        "category",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        nullable=False,
        postgresql_using="category::varchar(100)",
    )
    op.alter_column(
        "system_config",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )

    op.execute("DROP INDEX IF EXISTS idx_system_config_category")
    op.create_index(op.f("ix_system_config_key"), "system_config", ["key"], unique=True)
    # SAFE FIX: removed "ALTER TABLE system_config DROP COLUMN IF EXISTS updated_by"
    # This was CRITICAL destructive — dropping a column in production is
    # irreversible and would lose data. Instead, rename it to mark as deprecated.
    # The column can be safely dropped in a future migration after confirming
    # no code references it.
    op.execute("ALTER TABLE system_config RENAME COLUMN updated_by TO updated_by_deprecated")
    # ### end Alembic commands ###


def downgrade() -> None:
    # SAFE FIX: implemented proper downgrade (was empty 'pass')
    # Reverses all operations from upgrade() so rollback is possible.
    op.execute("ALTER TABLE system_config RENAME COLUMN updated_by_deprecated TO updated_by")
    op.drop_index(op.f("ix_system_config_key"), table_name="system_config")
    op.execute("CREATE INDEX IF NOT EXISTS idx_system_config_category ON system_config (category)")
    op.alter_column(
        "system_config",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "system_config",
        "category",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "system_config",
        "key",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.drop_column("system_config", "created_at")
    op.drop_column("system_config", "version")
    op.drop_column("system_config", "is_active")
    op.drop_column("system_config", "id")
    # ### end Alembic commands ###
