# ruff: noqa: BLE001, B904, E722
import asyncio

from fastapi import APIRouter
from fastapi import HTTPException
from github import Github  # PyGithub library
from pydantic import BaseModel

from core.messaging.pubsub import global_pubsub


# Adjusted imports to match your codebase


router = APIRouter(tags=["Dock Actions"])

class DockActionPayload(BaseModel):
    triggered_from: str
    active_file: str | None = None
    content: str | None = None # যে কোডটি গিটহাবে যাবে

# push_to_sse implemented using the global pubsub in your event system
async def push_to_sse(session_id: str, data: dict):
    await global_pubsub.publish("dashboard_events", {
        "type": "integration_status",
        "payload": {
            "session_id": session_id,
            **data
        }
    })

# NOTE: require_admin_token is currently mocked/commented for testing the UI
@router.post("/session/{session_id}/integrations/{tool_id}")
async def run_dock_integration(
    session_id: str, 
    tool_id: str, 
    payload: DockActionPayload,
    # token: str = Depends(require_admin_token)
):
    # ১. UI তে "Neon-Pulse" অ্যানিমেশন অন করার জন্য SSE পুশ
    await push_to_sse(session_id, {"state": "processing", "message": f"Connecting to {tool_id.capitalize()}..."})
    
    # ২. টুল ডিসপ্যাচার (Tool Dispatcher)
    if tool_id == "github":
        return await handle_github_push(session_id, payload)
    elif tool_id == "slack":
        raise HTTPException(status_code=501, detail="Slack not implemented yet")
    else:
        await push_to_sse(session_id, {"state": "error", "message": "Unknown tool"})
        raise HTTPException(status_code=400, detail="Integration not supported")


# --- গিটহাব ইন্টিগ্রেশন লজিক ---
async def handle_github_push(session_id: str, payload: DockActionPayload):
    try:
        # ধাপ ১: ইউজারের Vault থেকে গিটহাব টোকেন বের করা
        user_token = "ghp_your_personal_access_token" # (টেস্ট করার জন্য আপাতত হার্ডকোড করে দেখতে পারেন)

        if not user_token:
            raise ValueError("GitHub token missing! Please add it in your Vault.")

        # ধাপ ২: AI Agent দিয়ে কমিট মেসেজ জেনারেট করা
        file_name = payload.active_file or "snippet.ts"
        commit_message = f"🤖 SupremeAI Auto-Commit: Update {file_name}"
        file_content = payload.content or "// Auto-generated by SupremeAI Action Dock"

        # ধাপ ৩: গিটহাবে পুশ করা (PyGithub ম্যাজিক)
        await push_to_sse(session_id, {"state": "processing", "message": "Pushing code to repository..."})
        
        # PyGithub ব্লকিং কল করে, তাই এটিকে async এ চালানোর জন্য একটু ট্রিকস:
        def push_code():
            g = Github(user_token)
            user = g.get_user()
            # ইউজারের একটি ডিফল্ট রিপোজিটরি টার্গেট করুন, অথবা নতুন তৈরি করুন
            repo = user.get_repo("supremeai_generated_workspace") 
            
            try:
                # ফাইল আগে থাকলে আপডেট করবে, না থাকলে নতুন বানাবে
                contents = repo.get_contents(file_name)
                repo.update_file(contents.path, commit_message, file_content, contents.sha, branch="main")
            except:
                repo.create_file(file_name, commit_message, file_content, branch="main")

        # ব্যাকগ্রাউন্ড থ্রেডে গিটহাব এপিআই কল করা (যাতে ফাস্টএপিআই ব্লক না হয়)
        await asyncio.to_thread(push_code)

        # ধাপ ৪: UI তে সাকসেস মেসেজ ও গ্রিন টিক অ্যানিমেশন পাঠানো
        await push_to_sse(session_id, {"state": "success", "message": "Code successfully merged to GitHub!"})
        
        return {"ok": True, "message": "Pushed to GitHub"}

    except Exception as e:
        # ফেইলিউর অ্যানিমেশন ও এরর লগ
        error_msg = str(e)
        await push_to_sse(session_id, {"state": "error", "message": f"GitHub Error: {error_msg}"})
        raise HTTPException(status_code=500, detail=error_msg)

