#!/usr/bin/env python3
"""
SupremeAI - Context Snapshot Generator (Phase B)
================================================
যেকোনো বড় কাজ শুরুর আগে রান করুন।
শুধু task-প্রাসঙ্গিক ফাইলগুলোর সারসংক্ষেপ তৈরি করে context_snapshot.md-এ লেখে।
Token estimate দেখায় — AI-কে কতটুকু context দরকার তা বোঝা যায়।

Usage:
  python scripts/context_snapshot.py --task "fix-ci-pipeline"
  python scripts/context_snapshot.py --task "new-feature" --output my_snapshot.md
"""

import os
import math
import argparse
from datetime import datetime, timezone

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# কাজের ধরন → প্রাসঙ্গিক ফাইল ম্যাপ (Context Matrix from AGENTS.md)
TASK_FILE_MAP = {
    "bug-fix":   ["LESSONS_LEARNED.md", "KNOWN_ISSUES.md", "CHECKPOINT.md"],
    "debug":     ["LESSONS_LEARNED.md", "KNOWN_ISSUES.md", "CHECKPOINT.md"],
    "feature":   ["DECISION_LOG.md", "ARCHITECTURE.md", "CHECKPOINT.md"],
    "refactor":  ["DECISION_LOG.md", "ARCHITECTURE.md", "LESSONS_LEARNED.md", "CHECKPOINT.md"],
    "planning":  ["ACTION_PLAN.md", "TODO.md", "CHECKPOINT.md"],
    "roadmap":   ["ACTION_PLAN.md", "TODO.md", "CHECKPOINT.md"],
    "deploy":    ["DEPLOYMENT_CHECKLIST.md", "KNOWN_ISSUES.md", "CHECKPOINT.md"],
    "ci":        ["DEPLOYMENT_CHECKLIST.md", "KNOWN_ISSUES.md", "CHECKPOINT.md"],
    "general":   ["AGENTS.md", "CHECKPOINT.md"],
}

# সবসময় include করা হবে
ALWAYS_INCLUDE = ["AGENTS.md", "CHECKPOINT.md"]


def detect_task_type(task_description: str) -> str:
    """Task description থেকে task type detect করে।"""
    task_lower = task_description.lower()
    if any(k in task_lower for k in ["bug", "fix", "error", "crash", "fail"]):
        return "bug-fix"
    if any(k in task_lower for k in ["debug", "log", "trace"]):
        return "debug"
    if any(k in task_lower for k in ["feature", "add", "new", "implement"]):
        return "feature"
    if any(k in task_lower for k in ["refactor", "clean", "optimize", "dry"]):
        return "refactor"
    if any(k in task_lower for k in ["plan", "roadmap", "strategy"]):
        return "planning"
    if any(k in task_lower for k in ["deploy", "release", "production", "ci", "pipeline"]):
        return "deploy"
    return "general"


def read_file_summary(filepath: str, max_lines: int = 80) -> tuple[str, int]:
    """ফাইলের প্রথম max_lines লাইন পড়ে। token count সহ return করে।"""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            lines = f.readlines()

        total_lines = len(lines)
        content = "".join(lines[:max_lines])
        if total_lines > max_lines:
            content += f"\n... [truncated — {total_lines - max_lines} more lines]\n"

        word_count = len(content.split())
        token_estimate = math.ceil(word_count * 1.3)
        return content, token_estimate
    except FileNotFoundError:
        return f"(File not found: {filepath})\n", 5
    except Exception as e:
        return f"(Error reading file: {e})\n", 5


def generate_snapshot(task: str, output_file: str) -> None:
    """Context snapshot তৈরি করে।"""
    import sys
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    task_type = detect_task_type(task)
    relevant_files = list(dict.fromkeys(ALWAYS_INCLUDE + TASK_FILE_MAP.get(task_type, [])))

    print(f"[*] Task: '{task}'")
    print(f"[*] Detected type: {task_type}")
    print(f"[*] Loading {len(relevant_files)} relevant files...\n")

    total_tokens = 0
    sections = []

    for fname in relevant_files:
        fpath = os.path.join(ROOT_DIR, fname)
        content, tokens = read_file_summary(fpath, max_lines=60)
        total_tokens += tokens
        sections.append(f"## {fname} (~{tokens} tokens)\n\n```\n{content}\n```\n")
        print(f"  [OK] {fname}: ~{tokens} tokens")

    snapshot_content = f"""# SupremeAI Context Snapshot
> Generated: {now}
> Task: **{task}**
> Type: `{task_type}`
> Total Estimated Tokens: ~{total_tokens:,}

---

{"".join(sections)}

---
*Generated by `scripts/context_snapshot.py` — Phase B of SupremeAI Context Mesh*
"""

    output_path = os.path.join(ROOT_DIR, output_file)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(snapshot_content)

    print(f"\n{'='*50}")
    print(f"[OK] Snapshot saved: {output_file}")
    print(f"[*]  Total estimated tokens: ~{total_tokens:,}")

    if total_tokens > 200_000:
        print("[!]  WARNING: Large context -- use Gemini 1.5 Pro or Claude Sonnet")
    elif total_tokens > 100_000:
        print("[i]  TIP: Fits in GPT-4o / Claude Sonnet context window")
    else:
        print("[>>] Small context -- any LLM can handle this")
    print(f"{'='*50}\n")


def main():
    parser = argparse.ArgumentParser(description="SupremeAI Context Snapshot Generator")
    parser.add_argument("--task", "-t", type=str, default="general",
                        help="Task description (e.g., 'fix ci pipeline', 'new auth feature')")
    parser.add_argument("--output", "-o", type=str, default="context_snapshot.md",
                        help="Output filename (default: context_snapshot.md)")
    args = parser.parse_args()

    generate_snapshot(task=args.task, output_file=args.output)


if __name__ == "__main__":
    main()
