#!/usr/bin/env python3
"""Render MODULES_LIST.md from the governed wiring audit report."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUDIT_JSON = ROOT / "docs/audit_reports/module_wiring_audit.json"
MODULES_LIST = ROOT / "MODULES_LIST.md"


def evidence(items: list[str], noun: str) -> str:
    if not items:
        return f"0 active callers (dormant)" if noun == "caller" else "None"
    if len(items) <= 2:
        return ", ".join(items)
    return f"{len(items)} {noun}s ({items[0]}, ...)"


def sync_modules_list() -> None:
    data = json.loads(AUDIT_JSON.read_text(encoding="utf-8"))
    counts, modules, generated_at = data["counts"], data["modules"], data["generated_at"]
    lines = [
        "# SupremeAI - Comprehensive List of Modules", "", f"Total Modules: **{data['total']}**",
        f"**Truthful Operational Wiring Audit Summary ({generated_at}):**",
        f"- 🟢 **Operational:** {counts['operational']} modules (Importable + active inbound production callers)",
        f"- 🟡 **Environment-Dependent:** {counts['env_dependent']} modules (Requires external host service/token)",
        f"- 🟠 **Partially Wired (Dormant):** {counts['partially_wired']} modules (Importable; no active inbound production callers)",
        f"- 🔴 **Broken:** {counts['broken']} modules (Missing path or failed source validation)",
        f"- ⚪ **Planned:** {counts['planned']} modules (Architectural placeholder)", "",
        "<!-- Generated by scripts/sync_modules_list.py from docs/audit_reports/module_wiring_audit.json. -->", "",
        "| # | Category | Module Name / Relative Path | Operational Status | Caller Evidence | Test Evidence | Owner Circle | Decision |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for module in modules:
        lines.append("| " + " | ".join([
            str(module["id"]), module["category"], module["path"], module["status"],
            evidence(module.get("callers", []), "caller"), evidence(module.get("tests", []), "test"),
            module.get("owner_circle", "unassigned"), module.get("decision", "review"),
        ]) + " |")
    MODULES_LIST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[+] Updated MODULES_LIST.md with governed audit data ({data['total']} rows).")


if __name__ == "__main__":
    sync_modules_list()
