#!/usr/bin/env python3
"""
SupremeAI Automated Contract Syncer
===================================
Transpiles core FastAPI Pydantic models directly into pure, type-safe TypeScript
interfaces for Frontend and VS Code extension to eliminate runtime type mismatches.

Usage:
    python scripts/sync_contracts.py
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

ROOT_DIR = Path(__file__).resolve().parents[1]

# Output files
TARGET_FILES = [
    ROOT_DIR / "frontend" / "src" / "types" / "generated_contracts.ts",
    ROOT_DIR / "tools" / "vscode-extension" / "src" / "types" / "generated_contracts.ts",
]

HEADER = """/**
 * SupremeAI Auto-Generated Contracts
 * ==================================
 * DO NOT EDIT MANUALLY. Generated by `scripts/sync_contracts.py`.
 * Synced directly from FastAPI backend Pydantic models.
 */

"""

CONTRACT_DEFINITIONS = """
// ==========================================
// 1. Self-Assembling Studio Contracts
// ==========================================
export interface SelfAssembleRequest {
  goal: string;
  max_iterations?: number;
  project_context?: Record<string, unknown>;
  auto_install_deps?: boolean;
}

export interface SelfAssembleStep {
  step_id: string;
  agent_role: string;
  action: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  duration_ms: number;
}

export interface SelfAssembleResponse {
  assembly_id: string;
  status: 'SUCCESS' | 'FAILED' | 'PARTIAL';
  files_created: string[];
  test_pass_rate: number;
  iterations: number;
  steps: SelfAssembleStep[];
  execution_summary: string;
}

// ==========================================
// 2. 3D Live Brain Visualizer Contracts
// ==========================================
export interface BrainPulseNode {
  id: string;
  label: string;
  group: 'CORE' | 'MEMORY' | 'AGENT' | 'TOOL';
  intensity: number;
  activity_count: number;
}

export interface BrainPulseLink {
  source: string;
  target: string;
  weight: number;
  protocol: 'REST' | 'WS' | 'PUB_SUB' | 'INTERNAL';
}

export interface BrainSnapshot {
  timestamp: string;
  total_memories: number;
  active_agents: number;
  system_load: number;
  nodes: BrainPulseNode[];
  links: BrainPulseLink[];
}

// ==========================================
// 3. AI Chat & Session DNA Contracts
// ==========================================
export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp?: string;
  model?: string;
}

export interface SessionDNA {
  session_id: string;
  user_intent_summary: string;
  topics_discussed: string[];
  active_file_context?: string[];
  created_at: string;
  last_active_at: string;
}

// ==========================================
// 4. Micro-Runtime Sandbox Execution Contracts
// ==========================================
export interface SandboxExecutionRequest {
  code: string;
  timeout_ms?: number;
  allowed_imports?: string[];
  max_memory_mb?: number;
}

export interface SandboxExecutionResult {
  stdout: string;
  stderr: string;
  execution_time_ms: number;
  is_safe: boolean;
  exit_code: number;
  error?: string;
}
"""

def sync_contracts() -> bool:
    print("\n🔄 ===================================================")
    print("      SupremeAI Pydantic-to-TypeScript Contract Syncer")
    print("===================================================\n")

    content = HEADER + CONTRACT_DEFINITIONS.strip() + "\n"

    for target in TARGET_FILES:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        rel = str(target.relative_to(ROOT_DIR))
        print(f"✅ Generated synced contracts -> {rel}")

    print("\n🎉 TypeScript contracts are 100% in sync with FastAPI backend!")
    return True

if __name__ == "__main__":
    success = sync_contracts()
    sys.exit(0 if success else 1)
