name: _Test Minimal
on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: string
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.pr_number }}"
