name: Update PNPM Lockfile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Update Lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pnpm-lock.yaml
          git commit -m "chore: auto-update pnpm-lock.yaml" || echo "No changes to commit"
          git push
